<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Commune;



class CommuneSeeder extends Seeder
{
    public function run()
    {
        $communes = [
            ['name' => 'تيمقتن', 'wilaya_id' => 1],
            ['name' => 'بودة', 'wilaya_id' => 1],
            ['name' => 'أولاد أحمد تيمي', 'wilaya_id' => 1],
            ['name' => 'أدرار', 'wilaya_id' => 1],
            ['name' => 'فنوغيل', 'wilaya_id' => 1],
            ['name' => 'إن زغمير', 'wilaya_id' => 1],
            ['name' => 'رقان', 'wilaya_id' => 1],
            ['name' => 'سالي', 'wilaya_id' => 1],
            ['name' => 'السبع', 'wilaya_id' => 1],
            ['name' => 'تسابيت', 'wilaya_id' => 1],
            ['name' => 'تامست', 'wilaya_id' => 1],
            ['name' => 'تامنطيط', 'wilaya_id' => 1],
            ['name' => 'تيت', 'wilaya_id' => 1],
            ['name' => 'زاوية كنتة', 'wilaya_id' => 1],
            ['name' => 'اقبلي', 'wilaya_id' => 1],
            ['name' => 'أولف', 'wilaya_id' => 1],
            ['name' => 'تلعصة', 'wilaya_id' => 2],
            ['name' => 'الزبوجة', 'wilaya_id' => 2],
            ['name' => 'الحجاج', 'wilaya_id' => 2],
            ['name' => 'أولاد بن عبد القادر', 'wilaya_id' => 2],
            ['name' => 'عين مران', 'wilaya_id' => 2],
            ['name' => 'بريرة', 'wilaya_id' => 2],
            ['name' => 'أولاد عباس', 'wilaya_id' => 2],
            ['name' => 'وادي الفضة', 'wilaya_id' => 2],
            ['name' => 'بني راشد', 'wilaya_id' => 2],
            ['name' => 'الهرانفة', 'wilaya_id' => 2],
            ['name' => 'تاجنة', 'wilaya_id' => 2],
            ['name' => 'المرسى', 'wilaya_id' => 2],
            ['name' => 'الشلف', 'wilaya_id' => 2],
            ['name' => 'أم الدروع', 'wilaya_id' => 2],
            ['name' => 'سنجاس', 'wilaya_id' => 2],
            ['name' => 'سيدي عبد الرحمن', 'wilaya_id' => 2],
            ['name' => 'سيدي عكاشة', 'wilaya_id' => 2],
            ['name' => 'تنس', 'wilaya_id' => 2],
            ['name' => 'بني بوعتاب', 'wilaya_id' => 2],
            ['name' => 'الكريمية', 'wilaya_id' => 2],
            ['name' => 'حرشون', 'wilaya_id' => 2],
            ['name' => 'بوزغاية', 'wilaya_id' => 2],
            ['name' => 'تاوقريت', 'wilaya_id' => 2],
            ['name' => 'بني حواء', 'wilaya_id' => 2],
            ['name' => 'أبو الحسن', 'wilaya_id' => 2],
            ['name' => 'وادي قوسين', 'wilaya_id' => 2],
            ['name' => 'الشطية', 'wilaya_id' => 2],
            ['name' => 'مصدق', 'wilaya_id' => 2],
            ['name' => 'أولاد فارس', 'wilaya_id' => 2],
            ['name' => 'بوقادير', 'wilaya_id' => 2],
            ['name' => 'وادي سلي', 'wilaya_id' => 2],
            ['name' => 'الصبحة', 'wilaya_id' => 2],
            ['name' => 'بنايرية', 'wilaya_id' => 2],
            ['name' => 'الأبيض مجاجة', 'wilaya_id' => 2],
            ['name' => 'الظهرة', 'wilaya_id' => 2],
            ['name' => 'البيضاء', 'wilaya_id' => 3],
            ['name' => 'قلتة سيدي سعد', 'wilaya_id' => 3],
            ['name' => 'بريدة', 'wilaya_id' => 3],
            ['name' => 'عين سيدي علي', 'wilaya_id' => 3],
            ['name' => 'تاجموت', 'wilaya_id' => 3],
            ['name' => 'الحاج مشري', 'wilaya_id' => 3],
            ['name' => 'تاويالة', 'wilaya_id' => 3],
            ['name' => 'الغيشة', 'wilaya_id' => 3],
            ['name' => 'تاجرونة', 'wilaya_id' => 3],
            ['name' => 'سبقاق', 'wilaya_id' => 3],
            ['name' => 'سيدي بوزيد', 'wilaya_id' => 3],
            ['name' => 'وادي مرة', 'wilaya_id' => 3],
            ['name' => 'الأغواط', 'wilaya_id' => 3],
            ['name' => 'وادي مزي', 'wilaya_id' => 3],
            ['name' => 'قصر الحيران', 'wilaya_id' => 3],
            ['name' => 'العسافية', 'wilaya_id' => 3],
            ['name' => 'سيدي مخلوف', 'wilaya_id' => 3],
            ['name' => 'حاسي الدلاعة', 'wilaya_id' => 3],
            ['name' => 'حاسي الرمل', 'wilaya_id' => 3],
            ['name' => 'عين ماضي', 'wilaya_id' => 3],
            ['name' => 'الحويطة', 'wilaya_id' => 3],
            ['name' => 'الخنق', 'wilaya_id' => 3],
            ['name' => 'بن ناصر بن شهرة', 'wilaya_id' => 3],
            ['name' => 'أفلو', 'wilaya_id' => 3],
            ['name' => 'فكيرينة', 'wilaya_id' => 4],
            ['name' => 'الفجوج بوغرارة سعودي', 'wilaya_id' => 4],
            ['name' => 'عين فكرون', 'wilaya_id' => 4],
            ['name' => 'الرحية', 'wilaya_id' => 4],
            ['name' => 'مسكيانة', 'wilaya_id' => 4],
            ['name' => 'البلالة', 'wilaya_id' => 4],
            ['name' => 'بحير الشرقي', 'wilaya_id' => 4],
            ['name' => 'قصر الصباحي', 'wilaya_id' => 4],
            ['name' => 'سوق نعمان', 'wilaya_id' => 4],
            ['name' => 'أولاد زواي', 'wilaya_id' => 4],
            ['name' => 'أم البواقي', 'wilaya_id' => 4],
            ['name' => 'عين ببوش', 'wilaya_id' => 4],
            ['name' => 'عين الزيتون', 'wilaya_id' => 4],
            ['name' => 'بئر الشهداء', 'wilaya_id' => 4],
            ['name' => 'عين البيضاء', 'wilaya_id' => 4],
            ['name' => 'بريش', 'wilaya_id' => 4],
            ['name' => 'الزرق', 'wilaya_id' => 4],
            ['name' => 'عين مليلة', 'wilaya_id' => 4],
            ['name' => 'أولاد قاسم', 'wilaya_id' => 4],
            ['name' => 'أولاد حملة', 'wilaya_id' => 4],
            ['name' => 'العامرية', 'wilaya_id' => 4],
            ['name' => 'سيقوس', 'wilaya_id' => 4],
            ['name' => 'وادي نيني', 'wilaya_id' => 4],
            ['name' => 'عين الديس', 'wilaya_id' => 4],
            ['name' => 'الضلعة', 'wilaya_id' => 4],
            ['name' => 'الجازية', 'wilaya_id' => 4],
            ['name' => 'عين كرشة', 'wilaya_id' => 4],
            ['name' => 'الحرملية', 'wilaya_id' => 4],
            ['name' => 'هنشير تومغني', 'wilaya_id' => 4],
            ['name' => 'معافة', 'wilaya_id' => 5],
            ['name' => 'القصبات', 'wilaya_id' => 5],
            ['name' => 'تيمقاد', 'wilaya_id' => 5],
            ['name' => 'تاكسلانت', 'wilaya_id' => 5],
            ['name' => 'أولاد سي سليمان', 'wilaya_id' => 5],
            ['name' => 'لمسان', 'wilaya_id' => 5],
            ['name' => 'تالخمت', 'wilaya_id' => 5],
            ['name' => 'رأس العيون', 'wilaya_id' => 5],
            ['name' => 'الرحبات', 'wilaya_id' => 5],
            ['name' => 'أولاد سلام', 'wilaya_id' => 5],
            ['name' => 'القيقبة', 'wilaya_id' => 5],
            ['name' => 'ثنية العابد', 'wilaya_id' => 5],
            ['name' => 'باتنة', 'wilaya_id' => 5],
            ['name' => 'فسديس', 'wilaya_id' => 5],
            ['name' => 'وادي الشعبة', 'wilaya_id' => 5],
            ['name' => 'حيدوسة', 'wilaya_id' => 5],
            ['name' => 'قصر بلزمة', 'wilaya_id' => 5],
            ['name' => 'مروانة', 'wilaya_id' => 5],
            ['name' => 'وادي الماء', 'wilaya_id' => 5],
            ['name' => 'لازرو', 'wilaya_id' => 5],
            ['name' => 'سريانة', 'wilaya_id' => 5],
            ['name' => 'زانة البيضاء', 'wilaya_id' => 5],
            ['name' => 'منعة', 'wilaya_id' => 5],
            ['name' => 'تغرغار', 'wilaya_id' => 5],
            ['name' => 'عين ياقوت', 'wilaya_id' => 5],
            ['name' => 'بومية', 'wilaya_id' => 5],
            ['name' => 'جرمة', 'wilaya_id' => 5],
            ['name' => 'المعذر', 'wilaya_id' => 5],
            ['name' => 'عيون العصافير', 'wilaya_id' => 5],
            ['name' => 'تازولت', 'wilaya_id' => 5],
            ['name' => 'بومقر', 'wilaya_id' => 5],
            ['name' => 'نقاوس', 'wilaya_id' => 5],
            ['name' => 'سفيان', 'wilaya_id' => 5],
            ['name' => 'أريس', 'wilaya_id' => 5],
            ['name' => 'تيغانمين', 'wilaya_id' => 5],
            ['name' => 'عين جاسر', 'wilaya_id' => 5],
            ['name' => 'الحاسي', 'wilaya_id' => 5],
            ['name' => 'سقانة', 'wilaya_id' => 5],
            ['name' => 'تيلاطو', 'wilaya_id' => 5],
            ['name' => 'فم الطوب', 'wilaya_id' => 5],
            ['name' => 'إشمول', 'wilaya_id' => 5],
            ['name' => 'إينوغيسن', 'wilaya_id' => 5],
            ['name' => 'بوزينة', 'wilaya_id' => 5],
            ['name' => 'لارباع', 'wilaya_id' => 5],
            ['name' => 'بولهيلات', 'wilaya_id' => 5],
            ['name' => 'الشمرة', 'wilaya_id' => 5],
            ['name' => 'بريكة', 'wilaya_id' => 5],
            ['name' => 'بيطام', 'wilaya_id' => 5],
            ['name' => 'إمدوكل', 'wilaya_id' => 5],
            ['name' => 'عزيل عبد القادر', 'wilaya_id' => 5],
            ['name' => 'الجزار', 'wilaya_id' => 5],
            ['name' => 'أولاد عمار', 'wilaya_id' => 5],
            ['name' => 'غسيرة', 'wilaya_id' => 5],
            ['name' => 'كيمل', 'wilaya_id' => 5],
            ['name' => 'تكوت', 'wilaya_id' => 5],
            ['name' => 'عين التوتة', 'wilaya_id' => 5],
            ['name' => 'بني فضالة الحقانية', 'wilaya_id' => 5],
            ['name' => 'أولاد فاضل', 'wilaya_id' => 5],
            ['name' => 'أولاد عوف', 'wilaya_id' => 5],
            ['name' => 'شير', 'wilaya_id' => 5],
            ['name' => 'وادي الطاقة', 'wilaya_id' => 5],
            ['name' => 'سيدي عياد', 'wilaya_id' => 6],
            ['name' => 'برباشة', 'wilaya_id' => 6],
            ['name' => 'الفلاي', 'wilaya_id' => 6],
            ['name' => 'كنديرة', 'wilaya_id' => 6],
            ['name' => 'سيدي عيش', 'wilaya_id' => 6],
            ['name' => 'تيفرة', 'wilaya_id' => 6],
            ['name' => 'تينبدار', 'wilaya_id' => 6],
            ['name' => 'القصر', 'wilaya_id' => 6],
            ['name' => 'فناية الماثن', 'wilaya_id' => 6],
            ['name' => 'توجة', 'wilaya_id' => 6],
            ['name' => 'ذراع القايد', 'wilaya_id' => 6],
            ['name' => 'خراطة', 'wilaya_id' => 6],
            ['name' => 'بجاية', 'wilaya_id' => 6],
            ['name' => 'وادي غير', 'wilaya_id' => 6],
            ['name' => 'بني معوش', 'wilaya_id' => 6],
            ['name' => 'بني جليل', 'wilaya_id' => 6],
            ['name' => 'فرعون', 'wilaya_id' => 6],
            ['name' => 'سمعون', 'wilaya_id' => 6],
            ['name' => 'تيمزريت', 'wilaya_id' => 6],
            ['name' => 'مالبو', 'wilaya_id' => 6],
            ['name' => 'سوق لإثنين', 'wilaya_id' => 6],
            ['name' => 'تامريجت', 'wilaya_id' => 6],
            ['name' => 'بوخليفة', 'wilaya_id' => 6],
            ['name' => 'تالة حمزة', 'wilaya_id' => 6],
            ['name' => 'تيشي', 'wilaya_id' => 6],
            ['name' => 'أيت رزين', 'wilaya_id' => 6],
            ['name' => 'إغيل علي', 'wilaya_id' => 6],
            ['name' => 'أيت إسماعيل', 'wilaya_id' => 6],
            ['name' => 'درقينة', 'wilaya_id' => 6],
            ['name' => 'تاسكريوت', 'wilaya_id' => 6],
            ['name' => 'أوقاس', 'wilaya_id' => 6],
            ['name' => 'تيزي نبربر', 'wilaya_id' => 6],
            ['name' => 'أدكار', 'wilaya_id' => 6],
            ['name' => 'بني كسيلة', 'wilaya_id' => 6],
            ['name' => 'تاوريرت إغيل', 'wilaya_id' => 6],
            ['name' => 'أقبو', 'wilaya_id' => 6],
            ['name' => 'شلاطة', 'wilaya_id' => 6],
            ['name' => 'اغرم', 'wilaya_id' => 6],
            ['name' => 'تامقرة', 'wilaya_id' => 6],
            ['name' => 'أمالو', 'wilaya_id' => 6],
            ['name' => 'بوحمزة', 'wilaya_id' => 6],
            ['name' => 'مسيسنة', 'wilaya_id' => 6],
            ['name' => 'صدوق', 'wilaya_id' => 6],
            ['name' => 'بني مليكش', 'wilaya_id' => 6],
            ['name' => 'بو جليل', 'wilaya_id' => 6],
            ['name' => 'تازمالت', 'wilaya_id' => 6],
            ['name' => 'أكفادو', 'wilaya_id' => 6],
            ['name' => 'شميني', 'wilaya_id' => 6],
            ['name' => 'سوق اوفلا', 'wilaya_id' => 6],
            ['name' => 'طيبان', 'wilaya_id' => 6],
            ['name' => 'أوزلاقن', 'wilaya_id' => 6],
            ['name' => 'أميزور', 'wilaya_id' => 6],
            ['name' => 'الفيض', 'wilaya_id' => 7],
            ['name' => 'ليشانة', 'wilaya_id' => 7],
            ['name' => 'بوشقرون', 'wilaya_id' => 7],
            ['name' => 'مخادمة', 'wilaya_id' => 7],
            ['name' => 'جمورة', 'wilaya_id' => 7],
            ['name' => 'برانيس', 'wilaya_id' => 7],
            ['name' => 'الوطاية', 'wilaya_id' => 7],
            ['name' => 'القنطرة', 'wilaya_id' => 7],
            ['name' => 'خنقة سيدي ناجي', 'wilaya_id' => 7],
            ['name' => 'عين زعطوط', 'wilaya_id' => 7],
            ['name' => 'زريبة الوادي', 'wilaya_id' => 7],
            ['name' => 'المزيرعة', 'wilaya_id' => 7],
            ['name' => 'بسكرة', 'wilaya_id' => 7],
            ['name' => 'الحاجب', 'wilaya_id' => 7],
            ['name' => 'مليلي', 'wilaya_id' => 7],
            ['name' => 'فوغالة', 'wilaya_id' => 7],
            ['name' => 'الغروس', 'wilaya_id' => 7],
            ['name' => 'برج بن عزوز', 'wilaya_id' => 7],
            ['name' => 'أورلال', 'wilaya_id' => 7],
            ['name' => 'أوماش', 'wilaya_id' => 7],
            ['name' => 'عين الناقة', 'wilaya_id' => 7],
            ['name' => 'شتمة', 'wilaya_id' => 7],
            ['name' => 'الحوش', 'wilaya_id' => 7],
            ['name' => 'سيدي عقبة', 'wilaya_id' => 7],
            ['name' => 'مشونش', 'wilaya_id' => 7],
            ['name' => 'ليوة', 'wilaya_id' => 7],
            ['name' => 'طولقة', 'wilaya_id' => 7],
            ['name' => 'بشار', 'wilaya_id' => 8],
            ['name' => 'بوكايس', 'wilaya_id' => 8],
            ['name' => 'لحمر', 'wilaya_id' => 8],
            ['name' => 'موغل', 'wilaya_id' => 8],
            ['name' => 'المريجة', 'wilaya_id' => 8],
            ['name' => 'تاغيت', 'wilaya_id' => 8],
            ['name' => 'العبادلة', 'wilaya_id' => 8],
            ['name' => 'عرق فراج', 'wilaya_id' => 8],
            ['name' => 'مشرع هواري بومدين', 'wilaya_id' => 8],
            ['name' => 'بني ونيف', 'wilaya_id' => 8],
            ['name' => 'تبلبالة', 'wilaya_id' => 8],
            ['name' => 'القنادسة', 'wilaya_id' => 8],
            ['name' => 'بني مراد', 'wilaya_id' => 9],
            ['name' => 'اولاد سلامة', 'wilaya_id' => 9],
            ['name' => 'موزاية', 'wilaya_id' => 9],
            ['name' => 'حمام ملوان', 'wilaya_id' => 9],
            ['name' => 'بوقرة', 'wilaya_id' => 9],
            ['name' => 'صوحان', 'wilaya_id' => 9],
            ['name' => 'الأربعاء', 'wilaya_id' => 9],
            ['name' => 'الصومعة', 'wilaya_id' => 9],
            ['name' => 'قرواو', 'wilaya_id' => 9],
            ['name' => 'بوفاريك', 'wilaya_id' => 9],
            ['name' => 'مفتاح', 'wilaya_id' => 9],
            ['name' => 'الشفة', 'wilaya_id' => 9],
            ['name' => 'عين الرمانة', 'wilaya_id' => 9],
            ['name' => 'وادي جر', 'wilaya_id' => 9],
            ['name' => 'العفرون', 'wilaya_id' => 9],
            ['name' => 'أولاد يعيش', 'wilaya_id' => 9],
            ['name' => 'الشريعة', 'wilaya_id' => 9],
            ['name' => 'جبابرة', 'wilaya_id' => 9],
            ['name' => 'وادي العلايق', 'wilaya_id' => 9],
            ['name' => 'بن خليل', 'wilaya_id' => 9],
            ['name' => 'بني تامو', 'wilaya_id' => 9],
            ['name' => 'الشبلي', 'wilaya_id' => 9],
            ['name' => 'بوعينان', 'wilaya_id' => 9],
            ['name' => 'بوعرفة', 'wilaya_id' => 9],
            ['name' => 'البليدة', 'wilaya_id' => 9],
            ['name' => 'عين العلوي', 'wilaya_id' => 10],
            ['name' => 'الحجرة الزرقاء', 'wilaya_id' => 10],
            ['name' => 'مزدور', 'wilaya_id' => 10],
            ['name' => 'تاقديت', 'wilaya_id' => 10],
            ['name' => 'ريدان', 'wilaya_id' => 10],
            ['name' => 'المعمورة', 'wilaya_id' => 10],
            ['name' => 'الحاكمية', 'wilaya_id' => 10],
            ['name' => 'أهل القصر', 'wilaya_id' => 10],
            ['name' => 'ديرة', 'wilaya_id' => 10],
            ['name' => 'الدشمية', 'wilaya_id' => 10],
            ['name' => 'بشلول', 'wilaya_id' => 10],
            ['name' => 'آث  منصور', 'wilaya_id' => 10],
            ['name' => 'سحاريج', 'wilaya_id' => 10],
            ['name' => 'العجيبة', 'wilaya_id' => 10],
            ['name' => 'الأسنام', 'wilaya_id' => 10],
            ['name' => 'أمشدالة', 'wilaya_id' => 10],
            ['name' => 'برج أوخريص', 'wilaya_id' => 10],
            ['name' => 'سور الغزلان', 'wilaya_id' => 10],
            ['name' => 'حنيف', 'wilaya_id' => 10],
            ['name' => 'شرفة', 'wilaya_id' => 10],
            ['name' => 'أولاد راشد', 'wilaya_id' => 10],
            ['name' => 'عين الحجر', 'wilaya_id' => 10],
            ['name' => 'أغبالو', 'wilaya_id' => 10],
            ['name' => 'روراوة', 'wilaya_id' => 10],
            ['name' => 'الخبوزية', 'wilaya_id' => 10],
            ['name' => 'بئر غبالو', 'wilaya_id' => 10],
            ['name' => 'البويرة', 'wilaya_id' => 10],
            ['name' => 'عين الترك', 'wilaya_id' => 10],
            ['name' => 'أيت لعزيز', 'wilaya_id' => 10],
            ['name' => 'عين بسام', 'wilaya_id' => 10],
            ['name' => 'المقراني', 'wilaya_id' => 10],
            ['name' => 'سوق الخميس', 'wilaya_id' => 10],
            ['name' => 'أعمر', 'wilaya_id' => 10],
            ['name' => 'جباحية', 'wilaya_id' => 10],
            ['name' => 'الهاشمية', 'wilaya_id' => 10],
            ['name' => 'حيزر', 'wilaya_id' => 10],
            ['name' => 'تاغزوت', 'wilaya_id' => 10],
            ['name' => 'بودربالة', 'wilaya_id' => 10],
            ['name' => 'بوكرم', 'wilaya_id' => 10],
            ['name' => 'قرومة', 'wilaya_id' => 10],
            ['name' => 'الأخضرية', 'wilaya_id' => 10],
            ['name' => 'معلة', 'wilaya_id' => 10],
            ['name' => 'قادرية', 'wilaya_id' => 10],
            ['name' => 'زبربر', 'wilaya_id' => 10],
            ['name' => 'وادي البردي', 'wilaya_id' => 10],
            ['name' => 'تاظروك', 'wilaya_id' => 11],
            ['name' => 'ابلسة', 'wilaya_id' => 11],
            ['name' => 'تمنراست', 'wilaya_id' => 11],
            ['name' => 'عين امقل', 'wilaya_id' => 11],
            ['name' => 'أدلس', 'wilaya_id' => 11],
            ['name' => 'الحويجبات', 'wilaya_id' => 12],
            ['name' => 'العوينات', 'wilaya_id' => 12],
            ['name' => 'فركان', 'wilaya_id' => 12],
            ['name' => 'نقرين', 'wilaya_id' => 12],
            ['name' => 'بئر مقدم', 'wilaya_id' => 12],
            ['name' => 'بئر الذهب', 'wilaya_id' => 12],
            ['name' => 'صفصاف الوسرى', 'wilaya_id' => 12],
            ['name' => 'قريقر', 'wilaya_id' => 12],
            ['name' => 'بكارية', 'wilaya_id' => 12],
            ['name' => 'بولحاف الدير', 'wilaya_id' => 12],
            ['name' => 'أم علي', 'wilaya_id' => 12],
            ['name' => 'بوخضرة', 'wilaya_id' => 12],
            ['name' => 'الماء الابيض', 'wilaya_id' => 12],
            ['name' => 'الونزة', 'wilaya_id' => 12],
            ['name' => 'المريج', 'wilaya_id' => 12],
            ['name' => 'عين الزرقاء', 'wilaya_id' => 12],
            ['name' => 'سطح قنطيس', 'wilaya_id' => 12],
            ['name' => 'العقلة', 'wilaya_id' => 12],
            ['name' => 'المزرعة', 'wilaya_id' => 12],
            ['name' => 'بجن', 'wilaya_id' => 12],
            ['name' => 'مرسط', 'wilaya_id' => 12],
            ['name' => 'ثليجان', 'wilaya_id' => 12],
            ['name' => 'الشريعة', 'wilaya_id' => 12],
            ['name' => 'العقلة المالحة', 'wilaya_id' => 12],
            ['name' => 'بئر العاتر', 'wilaya_id' => 12],
            ['name' => 'تبسة', 'wilaya_id' => 12],
            ['name' => 'الحمامات', 'wilaya_id' => 12],
            ['name' => 'الكويف', 'wilaya_id' => 12],
            ['name' => 'باب العسة', 'wilaya_id' => 13],
            ['name' => 'تيرني بني هديل', 'wilaya_id' => 13],
            ['name' => 'منصورة', 'wilaya_id' => 13],
            ['name' => 'بني مستر', 'wilaya_id' => 13],
            ['name' => 'عين غرابة', 'wilaya_id' => 13],
            ['name' => 'شتوان', 'wilaya_id' => 13],
            ['name' => 'عمير', 'wilaya_id' => 13],
            ['name' => 'عين فزة', 'wilaya_id' => 13],
            ['name' => 'هنين', 'wilaya_id' => 13],
            ['name' => 'بني خلاد', 'wilaya_id' => 13],
            ['name' => 'سيدي الجيلالي', 'wilaya_id' => 13],
            ['name' => 'البويهي', 'wilaya_id' => 13],
            ['name' => 'ندرومة', 'wilaya_id' => 13],
            ['name' => 'مسيردة الفواقة', 'wilaya_id' => 13],
            ['name' => 'مرسى بن مهيدي', 'wilaya_id' => 13],
            ['name' => 'سيدي مجاهد', 'wilaya_id' => 13],
            ['name' => 'بني بوسعيد', 'wilaya_id' => 13],
            ['name' => 'سبدو', 'wilaya_id' => 13],
            ['name' => 'القور', 'wilaya_id' => 13],
            ['name' => 'العريشة', 'wilaya_id' => 13],
            ['name' => 'بوحلو', 'wilaya_id' => 13],
            ['name' => 'مغنية', 'wilaya_id' => 13],
            ['name' => 'حمام بوغرارة', 'wilaya_id' => 13],
            ['name' => 'زناتة', 'wilaya_id' => 13],
            ['name' => 'أولاد رياح', 'wilaya_id' => 13],
            ['name' => 'الحناية', 'wilaya_id' => 13],
            ['name' => 'سيدي العبدلي', 'wilaya_id' => 13],
            ['name' => 'سوق الثلاثاء', 'wilaya_id' => 13],
            ['name' => 'بن سكران', 'wilaya_id' => 13],
            ['name' => 'فلاوسن', 'wilaya_id' => 13],
            ['name' => 'عين الكبيرة', 'wilaya_id' => 13],
            ['name' => 'عين فتاح', 'wilaya_id' => 13],
            ['name' => 'تلمسان', 'wilaya_id' => 13],
            ['name' => 'عين النحالة', 'wilaya_id' => 13],
            ['name' => 'عين تالوت', 'wilaya_id' => 13],
            ['name' => 'عين يوسف', 'wilaya_id' => 13],
            ['name' => 'بني وارسوس', 'wilaya_id' => 13],
            ['name' => 'الفحول', 'wilaya_id' => 13],
            ['name' => 'الرمشي', 'wilaya_id' => 13],
            ['name' => 'سبعة شيوخ', 'wilaya_id' => 13],
            ['name' => 'السواني', 'wilaya_id' => 13],
            ['name' => 'صبرة', 'wilaya_id' => 13],
            ['name' => 'دار يغمراسن', 'wilaya_id' => 13],
            ['name' => 'الغزوات', 'wilaya_id' => 13],
            ['name' => 'السواحلية', 'wilaya_id' => 13],
            ['name' => 'تيانت', 'wilaya_id' => 13],
            ['name' => 'بني صميل', 'wilaya_id' => 13],
            ['name' => 'وادي الخضر', 'wilaya_id' => 13],
            ['name' => 'أولاد ميمون', 'wilaya_id' => 13],
            ['name' => 'بني بهدل', 'wilaya_id' => 13],
            ['name' => 'بني سنوس', 'wilaya_id' => 13],
            ['name' => 'العزايل', 'wilaya_id' => 13],
            ['name' => 'جبالة', 'wilaya_id' => 13],
            ['name' => 'مهدية', 'wilaya_id' => 14],
            ['name' => 'عين دزاريت', 'wilaya_id' => 14],
            ['name' => 'السبعين', 'wilaya_id' => 14],
            ['name' => 'الفايجة', 'wilaya_id' => 14],
            ['name' => 'سي عبد الغني', 'wilaya_id' => 14],
            ['name' => 'السوقر', 'wilaya_id' => 14],
            ['name' => 'توسنينة', 'wilaya_id' => 14],
            ['name' => 'مغيلة', 'wilaya_id' => 14],
            ['name' => 'السبت', 'wilaya_id' => 14],
            ['name' => 'سيدي حسني', 'wilaya_id' => 14],
            ['name' => 'عين الحديد', 'wilaya_id' => 14],
            ['name' => 'فرندة', 'wilaya_id' => 14],
            ['name' => 'تخمرت', 'wilaya_id' => 14],
            ['name' => 'عين كرمس', 'wilaya_id' => 14],
            ['name' => 'جبيلات الرصفاء', 'wilaya_id' => 14],
            ['name' => 'مادنة', 'wilaya_id' => 14],
            ['name' => 'مدريسة', 'wilaya_id' => 14],
            ['name' => 'سيدي عبد الرحمن', 'wilaya_id' => 14],
            ['name' => 'قصر الشلالة', 'wilaya_id' => 14],
            ['name' => 'قرطوفة', 'wilaya_id' => 14],
            ['name' => 'سرغين', 'wilaya_id' => 14],
            ['name' => 'زمالة  الأمير عبد القادر', 'wilaya_id' => 14],
            ['name' => 'وادي ليلي', 'wilaya_id' => 14],
            ['name' => 'سيدي علي ملال', 'wilaya_id' => 14],
            ['name' => 'جيلالي بن عمار', 'wilaya_id' => 14],
            ['name' => 'مشرع الصفا', 'wilaya_id' => 14],
            ['name' => 'تاقدمت', 'wilaya_id' => 14],
            ['name' => 'بوقرة', 'wilaya_id' => 14],
            ['name' => 'حمادية', 'wilaya_id' => 14],
            ['name' => 'الرشايقة', 'wilaya_id' => 14],
            ['name' => 'تيدة', 'wilaya_id' => 14],
            ['name' => 'الناظورة', 'wilaya_id' => 14],
            ['name' => 'تيارت', 'wilaya_id' => 14],
            ['name' => 'مدروسة', 'wilaya_id' => 14],
            ['name' => 'ملاكو', 'wilaya_id' => 14],
            ['name' => 'سيدي بختي', 'wilaya_id' => 14],
            ['name' => 'عين الذهب', 'wilaya_id' => 14],
            ['name' => 'شحيمة', 'wilaya_id' => 14],
            ['name' => 'النعيمة', 'wilaya_id' => 14],
            ['name' => 'عين بوشقيف', 'wilaya_id' => 14],
            ['name' => 'دحموني', 'wilaya_id' => 14],
            ['name' => 'الرحوية', 'wilaya_id' => 14],
            ['name' => 'ميزرانـــة', 'wilaya_id' => 15],
            ['name' => 'إيجــار', 'wilaya_id' => 15],
            ['name' => 'بني دوالة', 'wilaya_id' => 15],
            ['name' => 'بني زيكــي', 'wilaya_id' => 15],
            ['name' => 'إيلولة أومـــالو', 'wilaya_id' => 15],
            ['name' => 'أقني قغران', 'wilaya_id' => 15],
            ['name' => 'أيت بــوادو', 'wilaya_id' => 15],
            ['name' => 'واضية', 'wilaya_id' => 15],
            ['name' => 'تيزي نثلاثة', 'wilaya_id' => 15],
            ['name' => 'أغريب', 'wilaya_id' => 15],
            ['name' => 'أيت شافع', 'wilaya_id' => 15],
            ['name' => 'أقرو', 'wilaya_id' => 15],
            ['name' => 'أزفون', 'wilaya_id' => 15],
            ['name' => 'إفليـــسن', 'wilaya_id' => 15],
            ['name' => 'تيقـزيرت', 'wilaya_id' => 15],
            ['name' => 'أسي يوسف', 'wilaya_id' => 15],
            ['name' => 'بوغني', 'wilaya_id' => 15],
            ['name' => 'بونوح', 'wilaya_id' => 15],
            ['name' => 'مشطراس', 'wilaya_id' => 15],
            ['name' => 'ذراع بن خدة', 'wilaya_id' => 15],
            ['name' => 'سيدي نعمان', 'wilaya_id' => 15],
            ['name' => 'تادمايت', 'wilaya_id' => 15],
            ['name' => 'تيرمتين', 'wilaya_id' => 15],
            ['name' => 'أيت بومهدي', 'wilaya_id' => 15],
            ['name' => 'أيت تودرت', 'wilaya_id' => 15],
            ['name' => 'بني عيسي', 'wilaya_id' => 15],
            ['name' => 'واسيف', 'wilaya_id' => 15],
            ['name' => 'أيت خليلي', 'wilaya_id' => 15],
            ['name' => 'مقــلع', 'wilaya_id' => 15],
            ['name' => 'صوامـــع', 'wilaya_id' => 15],
            ['name' => 'بني يني', 'wilaya_id' => 15],
            ['name' => 'إبودرارن', 'wilaya_id' => 15],
            ['name' => 'تيزي وزو', 'wilaya_id' => 15],
            ['name' => 'أبي يوسف', 'wilaya_id' => 15],
            ['name' => 'عين الحمام', 'wilaya_id' => 15],
            ['name' => 'أيت يحيى', 'wilaya_id' => 15],
            ['name' => 'اقبيل', 'wilaya_id' => 15],
            ['name' => 'بوجيمة', 'wilaya_id' => 15],
            ['name' => 'ماكودة', 'wilaya_id' => 15],
            ['name' => 'عين الزاوية', 'wilaya_id' => 15],
            ['name' => 'أيت يحي موسى', 'wilaya_id' => 15],
            ['name' => 'ذراع الميزان', 'wilaya_id' => 15],
            ['name' => 'فريقات', 'wilaya_id' => 15],
            ['name' => 'مكيرة', 'wilaya_id' => 15],
            ['name' => 'تيزي غنيف', 'wilaya_id' => 15],
            ['name' => 'يطــافن', 'wilaya_id' => 15],
            ['name' => 'إيلـيــلتـن', 'wilaya_id' => 15],
            ['name' => 'إمســوحال', 'wilaya_id' => 15],
            ['name' => 'عزازقة', 'wilaya_id' => 15],
            ['name' => 'فريحة', 'wilaya_id' => 15],
            ['name' => 'إيفيغاء', 'wilaya_id' => 15],
            ['name' => 'إعــكورن', 'wilaya_id' => 15],
            ['name' => 'زكري', 'wilaya_id' => 15],
            ['name' => 'أيت عقـواشة', 'wilaya_id' => 15],
            ['name' => 'إيرجـــن', 'wilaya_id' => 15],
            ['name' => 'الأربعــاء ناث إيراثن', 'wilaya_id' => 15],
            ['name' => 'أيت  أومالو', 'wilaya_id' => 15],
            ['name' => 'تيزي راشد', 'wilaya_id' => 15],
            ['name' => 'أيت عيسى ميمون', 'wilaya_id' => 15],
            ['name' => 'واقنون', 'wilaya_id' => 15],
            ['name' => 'تيمـيزار', 'wilaya_id' => 15],
            ['name' => 'معـــاتقة', 'wilaya_id' => 15],
            ['name' => 'سوق الإثنين', 'wilaya_id' => 15],
            ['name' => 'أيت محمود', 'wilaya_id' => 15],
            ['name' => 'بنــــي زمنزار', 'wilaya_id' => 15],
            ['name' => 'إفــرحــونان', 'wilaya_id' => 15],
            ['name' => 'بوزقــن', 'wilaya_id' => 15],
            ['name' => 'حسين داي', 'wilaya_id' => 16],
            ['name' => 'الكاليتوس', 'wilaya_id' => 16],
            ['name' => 'سيدي موسى', 'wilaya_id' => 16],
            ['name' => 'القبة', 'wilaya_id' => 16],
            ['name' => 'محمد بلوزداد', 'wilaya_id' => 16],
            ['name' => 'عين طاية', 'wilaya_id' => 16],
            ['name' => 'باب الزوار', 'wilaya_id' => 16],
            ['name' => 'برج الكيفان', 'wilaya_id' => 16],
            ['name' => 'الدار البيضاء', 'wilaya_id' => 16],
            ['name' => 'المرسى', 'wilaya_id' => 16],
            ['name' => 'المحمدية', 'wilaya_id' => 16],
            ['name' => 'بئر توتة', 'wilaya_id' => 16],
            ['name' => 'اولاد شبل', 'wilaya_id' => 16],
            ['name' => 'تسالة المرجة', 'wilaya_id' => 16],
            ['name' => 'هراوة', 'wilaya_id' => 16],
            ['name' => 'رغاية', 'wilaya_id' => 16],
            ['name' => 'الرويبة', 'wilaya_id' => 16],
            ['name' => 'المعالمة', 'wilaya_id' => 16],
            ['name' => 'الرحمانية', 'wilaya_id' => 16],
            ['name' => 'سويدانية', 'wilaya_id' => 16],
            ['name' => 'سطاوالي', 'wilaya_id' => 16],
            ['name' => 'زرالدة', 'wilaya_id' => 16],
            ['name' => 'بابا حسن', 'wilaya_id' => 16],
            ['name' => 'الدويرة', 'wilaya_id' => 16],
            ['name' => 'الدرارية', 'wilaya_id' => 16],
            ['name' => 'العاشور', 'wilaya_id' => 16],
            ['name' => 'الخرايسية', 'wilaya_id' => 16],
            ['name' => 'عين بنيان', 'wilaya_id' => 16],
            ['name' => 'الشراقة', 'wilaya_id' => 16],
            ['name' => 'دالي ابراهيم', 'wilaya_id' => 16],
            ['name' => 'الحمامات', 'wilaya_id' => 16],
            ['name' => 'اولاد فايت', 'wilaya_id' => 16],
            ['name' => 'الجزائر الوسطى', 'wilaya_id' => 16],
            ['name' => 'المدنية', 'wilaya_id' => 16],
            ['name' => 'المرادية', 'wilaya_id' => 16],
            ['name' => 'سيدي امحمد', 'wilaya_id' => 16],
            ['name' => 'السحاولة', 'wilaya_id' => 16],
            ['name' => 'بولوغين بن زيري', 'wilaya_id' => 16],
            ['name' => 'القصبة', 'wilaya_id' => 16],
            ['name' => 'وادي قريش', 'wilaya_id' => 16],
            ['name' => 'الرايس حميدو', 'wilaya_id' => 16],
            ['name' => 'بئر مراد رايس', 'wilaya_id' => 16],
            ['name' => 'بئر خادم', 'wilaya_id' => 16],
            ['name' => 'جسر قسنطينة', 'wilaya_id' => 16],
            ['name' => 'حيدرة', 'wilaya_id' => 16],
            ['name' => 'المغارية', 'wilaya_id' => 16],
            ['name' => 'ابن عكنون', 'wilaya_id' => 16],
            ['name' => 'بني مسوس', 'wilaya_id' => 16],
            ['name' => 'بوزريعة', 'wilaya_id' => 16],
            ['name' => 'الابيار', 'wilaya_id' => 16],
            ['name' => 'باش جراح', 'wilaya_id' => 16],
            ['name' => 'بوروبة', 'wilaya_id' => 16],
            ['name' => 'الحراش', 'wilaya_id' => 16],
            ['name' => 'وادي السمار', 'wilaya_id' => 16],
            ['name' => 'براقي', 'wilaya_id' => 16],
            ['name' => 'برج البحري', 'wilaya_id' => 16],
            ['name' => 'باب الوادي', 'wilaya_id' => 16],
            ['name' => 'حاسي العش', 'wilaya_id' => 17],
            ['name' => 'عين الإبل', 'wilaya_id' => 17],
            ['name' => 'القديد', 'wilaya_id' => 17],
            ['name' => 'الشارف', 'wilaya_id' => 17],
            ['name' => 'بن يعقوب', 'wilaya_id' => 17],
            ['name' => 'سيدي بايزيد', 'wilaya_id' => 17],
            ['name' => 'مليليحة', 'wilaya_id' => 17],
            ['name' => 'دار الشيوخ', 'wilaya_id' => 17],
            ['name' => 'تعظميت', 'wilaya_id' => 17],
            ['name' => 'حد الصحاري', 'wilaya_id' => 17],
            ['name' => 'بويرة الأحداب', 'wilaya_id' => 17],
            ['name' => 'عين فقه', 'wilaya_id' => 17],
            ['name' => 'سيدي لعجال', 'wilaya_id' => 17],
            ['name' => 'حاسي فدول', 'wilaya_id' => 17],
            ['name' => 'الخميس', 'wilaya_id' => 17],
            ['name' => 'سلمانة', 'wilaya_id' => 17],
            ['name' => 'سد الرحال', 'wilaya_id' => 17],
            ['name' => 'مسعد', 'wilaya_id' => 17],
            ['name' => 'قطارة', 'wilaya_id' => 17],
            ['name' => 'دلدول', 'wilaya_id' => 17],
            ['name' => 'زكار', 'wilaya_id' => 17],
            ['name' => 'دويس', 'wilaya_id' => 17],
            ['name' => 'الادريسية', 'wilaya_id' => 17],
            ['name' => 'عين الشهداء', 'wilaya_id' => 17],
            ['name' => 'الجلفة', 'wilaya_id' => 17],
            ['name' => 'بيرين', 'wilaya_id' => 17],
            ['name' => 'أم العظام', 'wilaya_id' => 17],
            ['name' => 'فيض البطمة', 'wilaya_id' => 17],
            ['name' => 'عمورة', 'wilaya_id' => 17],
            ['name' => 'زعفران', 'wilaya_id' => 17],
            ['name' => 'قرنيني', 'wilaya_id' => 17],
            ['name' => 'عين وسارة', 'wilaya_id' => 17],
            ['name' => 'بنهار', 'wilaya_id' => 17],
            ['name' => 'عين معبد', 'wilaya_id' => 17],
            ['name' => 'حاسي بحبح', 'wilaya_id' => 17],
            ['name' => 'مجبارة', 'wilaya_id' => 17],
            ['name' => 'جيجل', 'wilaya_id' => 18],
            ['name' => 'العوانة', 'wilaya_id' => 18],
            ['name' => 'سلمى بن زيادة', 'wilaya_id' => 18],
            ['name' => 'أراقن سويسي', 'wilaya_id' => 18],
            ['name' => 'بوسيف أولاد عسكر', 'wilaya_id' => 18],
            ['name' => 'زيامة منصورية', 'wilaya_id' => 18],
            ['name' => 'الشحنة', 'wilaya_id' => 18],
            ['name' => 'الامير عبد القادر', 'wilaya_id' => 18],
            ['name' => 'وجانة', 'wilaya_id' => 18],
            ['name' => 'الطاهير', 'wilaya_id' => 18],
            ['name' => 'الشقفة', 'wilaya_id' => 18],
            ['name' => 'القنار نشفي', 'wilaya_id' => 18],
            ['name' => 'سيدي عبد العزيز', 'wilaya_id' => 18],
            ['name' => 'الميلية', 'wilaya_id' => 18],
            ['name' => 'أولاد يحيى خدروش', 'wilaya_id' => 18],
            ['name' => 'أولاد رابح', 'wilaya_id' => 18],
            ['name' => 'سيدي معروف', 'wilaya_id' => 18],
            ['name' => 'غبالة', 'wilaya_id' => 18],
            ['name' => 'السطارة', 'wilaya_id' => 18],
            ['name' => 'بوراوي بلهادف', 'wilaya_id' => 18],
            ['name' => 'العنصر', 'wilaya_id' => 18],
            ['name' => 'خيري واد عجول', 'wilaya_id' => 18],
            ['name' => 'جيملة', 'wilaya_id' => 18],
            ['name' => 'قاوس', 'wilaya_id' => 18],
            ['name' => 'تاكسنة', 'wilaya_id' => 18],
            ['name' => 'برج الطهر', 'wilaya_id' => 18],
            ['name' => 'بودريعة بني  ياجيس', 'wilaya_id' => 18],
            ['name' => 'الجمعة بني حبيبي', 'wilaya_id' => 18],
            ['name' => 'الرصفة', 'wilaya_id' => 19],
            ['name' => 'واد البارد', 'wilaya_id' => 19],
            ['name' => 'تيزي نبشار', 'wilaya_id' => 19],
            ['name' => 'مزلوق', 'wilaya_id' => 19],
            ['name' => 'قلال', 'wilaya_id' => 19],
            ['name' => 'قصر الابطال', 'wilaya_id' => 19],
            ['name' => 'أولاد سي أحمد', 'wilaya_id' => 19],
            ['name' => 'أيت نوال مزادة', 'wilaya_id' => 19],
            ['name' => 'ايت تيزي', 'wilaya_id' => 19],
            ['name' => 'بوعنداس', 'wilaya_id' => 19],
            ['name' => 'بوسلام', 'wilaya_id' => 19],
            ['name' => 'حمام السخنة', 'wilaya_id' => 19],
            ['name' => 'الطاية', 'wilaya_id' => 19],
            ['name' => 'التلة', 'wilaya_id' => 19],
            ['name' => 'عين ولمان', 'wilaya_id' => 19],
            ['name' => 'بوطالب', 'wilaya_id' => 19],
            ['name' => 'الحامة', 'wilaya_id' => 19],
            ['name' => 'أولاد تبان', 'wilaya_id' => 19],
            ['name' => 'عموشة', 'wilaya_id' => 19],
            ['name' => 'صالح باي', 'wilaya_id' => 19],
            ['name' => 'عين أزال', 'wilaya_id' => 19],
            ['name' => 'عين الحجر', 'wilaya_id' => 19],
            ['name' => 'بيضاء برج', 'wilaya_id' => 19],
            ['name' => 'بئر حدادة', 'wilaya_id' => 19],
            ['name' => 'قنزات', 'wilaya_id' => 19],
            ['name' => 'حربيل', 'wilaya_id' => 19],
            ['name' => 'عين الروى', 'wilaya_id' => 19],
            ['name' => 'بني وسين', 'wilaya_id' => 19],
            ['name' => 'أوريسيا', 'wilaya_id' => 19],
            ['name' => 'بوقاعة', 'wilaya_id' => 19],
            ['name' => 'ذراع قبيلة', 'wilaya_id' => 19],
            ['name' => 'حمام قرقور', 'wilaya_id' => 19],
            ['name' => 'سطيف', 'wilaya_id' => 19],
            ['name' => 'عين الكبيرة', 'wilaya_id' => 19],
            ['name' => 'الدهامشة', 'wilaya_id' => 19],
            ['name' => 'أولاد عدوان', 'wilaya_id' => 19],
            ['name' => 'عين السبت', 'wilaya_id' => 19],
            ['name' => 'بني عزيز', 'wilaya_id' => 19],
            ['name' => 'معاوية', 'wilaya_id' => 19],
            ['name' => 'بلاعة', 'wilaya_id' => 19],
            ['name' => 'بئر العرش', 'wilaya_id' => 19],
            ['name' => 'الولجة', 'wilaya_id' => 19],
            ['name' => 'تاشودة', 'wilaya_id' => 19],
            ['name' => 'تالة إيفاسن', 'wilaya_id' => 19],
            ['name' => 'سرج الغول', 'wilaya_id' => 19],
            ['name' => 'قجال', 'wilaya_id' => 19],
            ['name' => 'أولاد صابر', 'wilaya_id' => 19],
            ['name' => 'بازر سكرة', 'wilaya_id' => 19],
            ['name' => 'العلمة', 'wilaya_id' => 19],
            ['name' => 'قلتة زرقاء', 'wilaya_id' => 19],
            ['name' => 'بني فودة', 'wilaya_id' => 19],
            ['name' => 'جميلة', 'wilaya_id' => 19],
            ['name' => 'عين لقراج', 'wilaya_id' => 19],
            ['name' => 'بني شبانة', 'wilaya_id' => 19],
            ['name' => 'بني ورتيلان', 'wilaya_id' => 19],
            ['name' => 'بني موحلي', 'wilaya_id' => 19],
            ['name' => 'عين عباسة', 'wilaya_id' => 19],
            ['name' => 'عين أرنات', 'wilaya_id' => 19],
            ['name' => 'بابور', 'wilaya_id' => 19],
            ['name' => 'ماوكلان', 'wilaya_id' => 19],
            ['name' => 'سعيدة', 'wilaya_id' => 20],
            ['name' => 'تيرسين', 'wilaya_id' => 20],
            ['name' => 'أولاد إبراهيم', 'wilaya_id' => 20],
            ['name' => 'عين السلطان', 'wilaya_id' => 20],
            ['name' => 'المعمورة', 'wilaya_id' => 20],
            ['name' => 'الحساسنة', 'wilaya_id' => 20],
            ['name' => 'عين السخونة', 'wilaya_id' => 20],
            ['name' => 'سيدي بوبكر', 'wilaya_id' => 20],
            ['name' => 'أولاد خالد', 'wilaya_id' => 20],
            ['name' => 'هونت', 'wilaya_id' => 20],
            ['name' => 'يوب', 'wilaya_id' => 20],
            ['name' => 'دوي ثابت', 'wilaya_id' => 20],
            ['name' => 'سيدي احمد', 'wilaya_id' => 20],
            ['name' => 'مولاي العربي', 'wilaya_id' => 20],
            ['name' => 'عين الحجر', 'wilaya_id' => 20],
            ['name' => 'سيدي عمر', 'wilaya_id' => 20],
            ['name' => 'عين بوزيان', 'wilaya_id' => 21],
            ['name' => 'صالح بو الشعور', 'wilaya_id' => 21],
            ['name' => 'الحدائق', 'wilaya_id' => 21],
            ['name' => 'زردازة', 'wilaya_id' => 21],
            ['name' => 'أولاد حبابة', 'wilaya_id' => 21],
            ['name' => 'بني ولبان', 'wilaya_id' => 21],
            ['name' => 'سيدي مزغيش', 'wilaya_id' => 21],
            ['name' => 'بني بشير', 'wilaya_id' => 21],
            ['name' => 'رمضان جمال', 'wilaya_id' => 21],
            ['name' => 'بين الويدان', 'wilaya_id' => 21],
            ['name' => 'مجاز الدشيش', 'wilaya_id' => 21],
            ['name' => 'تمالوس', 'wilaya_id' => 21],
            ['name' => 'عين قشرة', 'wilaya_id' => 21],
            ['name' => 'الولجة بولبلوط', 'wilaya_id' => 21],
            ['name' => 'أم الطوب', 'wilaya_id' => 21],
            ['name' => 'الغدير', 'wilaya_id' => 21],
            ['name' => 'الكركرة', 'wilaya_id' => 21],
            ['name' => 'الحروش', 'wilaya_id' => 21],
            ['name' => 'الزيتونة', 'wilaya_id' => 21],
            ['name' => 'أولاد عطية', 'wilaya_id' => 21],
            ['name' => 'وادي الزهور', 'wilaya_id' => 21],
            ['name' => 'القل', 'wilaya_id' => 21],
            ['name' => 'الشرايع', 'wilaya_id' => 21],
            ['name' => 'بني زيد', 'wilaya_id' => 21],
            ['name' => 'خناق مايو', 'wilaya_id' => 21],
            ['name' => 'المرسى', 'wilaya_id' => 21],
            ['name' => 'بن عزوز', 'wilaya_id' => 21],
            ['name' => 'بكوش لخضر', 'wilaya_id' => 21],
            ['name' => 'السبت', 'wilaya_id' => 21],
            ['name' => 'عين شرشار', 'wilaya_id' => 21],
            ['name' => 'عزابة', 'wilaya_id' => 21],
            ['name' => 'بوشطاطة', 'wilaya_id' => 21],
            ['name' => 'فلفلة', 'wilaya_id' => 21],
            ['name' => 'حمادي كرومة', 'wilaya_id' => 21],
            ['name' => 'سكيكدة', 'wilaya_id' => 21],
            ['name' => 'عين زويت', 'wilaya_id' => 21],
            ['name' => 'جندل سعدي محمد', 'wilaya_id' => 21],
            ['name' => 'قنواع', 'wilaya_id' => 21],
            ['name' => 'سيدي علي بن يوب', 'wilaya_id' => 22],
            ['name' => 'مولاي سليسن', 'wilaya_id' => 22],
            ['name' => 'الحصيبة', 'wilaya_id' => 22],
            ['name' => 'عين تندمين', 'wilaya_id' => 22],
            ['name' => 'تنيرة', 'wilaya_id' => 22],
            ['name' => 'وادي سفيون', 'wilaya_id' => 22],
            ['name' => 'حاسي دحو', 'wilaya_id' => 22],
            ['name' => 'وادي تاوريرة', 'wilaya_id' => 22],
            ['name' => 'بن عشيبة شلية', 'wilaya_id' => 22],
            ['name' => 'سيدي يعقوب', 'wilaya_id' => 22],
            ['name' => 'سيدي لحسن', 'wilaya_id' => 22],
            ['name' => 'سيدي خالد', 'wilaya_id' => 22],
            ['name' => 'طابية', 'wilaya_id' => 22],
            ['name' => 'سيدي ابراهيم', 'wilaya_id' => 22],
            ['name' => 'العمارنة', 'wilaya_id' => 22],
            ['name' => 'بوخنفيس', 'wilaya_id' => 22],
            ['name' => 'حاسي زهانة', 'wilaya_id' => 22],
            ['name' => 'شيطوان البلايلة', 'wilaya_id' => 22],
            ['name' => 'بن باديس', 'wilaya_id' => 22],
            ['name' => 'بضرابين المقراني', 'wilaya_id' => 22],
            ['name' => 'سفيزف', 'wilaya_id' => 22],
            ['name' => 'مسيد', 'wilaya_id' => 22],
            ['name' => 'بوجبهة البرج', 'wilaya_id' => 22],
            ['name' => 'عين أدن', 'wilaya_id' => 22],
            ['name' => 'سيدي حمادوش', 'wilaya_id' => 22],
            ['name' => 'سيدي شعيب', 'wilaya_id' => 22],
            ['name' => 'مكدرة', 'wilaya_id' => 22],
            ['name' => 'عين البرد', 'wilaya_id' => 22],
            ['name' => 'رجم دموش', 'wilaya_id' => 22],
            ['name' => 'راس الماء', 'wilaya_id' => 22],
            ['name' => 'وادي السبع', 'wilaya_id' => 22],
            ['name' => 'مرحوم', 'wilaya_id' => 22],
            ['name' => 'سيدي بلعباس', 'wilaya_id' => 22],
            ['name' => 'عين الثريد', 'wilaya_id' => 22],
            ['name' => 'السهالة الثورة', 'wilaya_id' => 22],
            ['name' => 'تسالة', 'wilaya_id' => 22],
            ['name' => 'بلعربي', 'wilaya_id' => 22],
            ['name' => 'مصطفى بن ابراهيم', 'wilaya_id' => 22],
            ['name' => 'تلموني', 'wilaya_id' => 22],
            ['name' => 'زروالة', 'wilaya_id' => 22],
            ['name' => 'الضاية', 'wilaya_id' => 22],
            ['name' => 'مزاورو', 'wilaya_id' => 22],
            ['name' => 'تغاليمت', 'wilaya_id' => 22],
            ['name' => 'تلاغ', 'wilaya_id' => 22],
            ['name' => 'عين قادة', 'wilaya_id' => 22],
            ['name' => 'لمطار', 'wilaya_id' => 22],
            ['name' => 'سيدي علي بوسيدي', 'wilaya_id' => 22],
            ['name' => 'سيدي دحو الزاير', 'wilaya_id' => 22],
            ['name' => 'بئر الحمام', 'wilaya_id' => 22],
            ['name' => 'مرين', 'wilaya_id' => 22],
            ['name' => 'تفسور', 'wilaya_id' => 22],
            ['name' => 'تاودموت', 'wilaya_id' => 22],
            ['name' => 'عنابة', 'wilaya_id' => 23],
            ['name' => 'سرايدي', 'wilaya_id' => 23],
            ['name' => 'برحال', 'wilaya_id' => 23],
            ['name' => 'واد العنب', 'wilaya_id' => 23],
            ['name' => 'الحجار', 'wilaya_id' => 23],
            ['name' => 'سيدي عمار', 'wilaya_id' => 23],
            ['name' => 'البوني', 'wilaya_id' => 23],
            ['name' => 'عين الباردة', 'wilaya_id' => 23],
            ['name' => 'الشرفة', 'wilaya_id' => 23],
            ['name' => 'العلمة', 'wilaya_id' => 23],
            ['name' => 'التريعات', 'wilaya_id' => 23],
            ['name' => 'شطايبي', 'wilaya_id' => 23],
            ['name' => 'نشماية', 'wilaya_id' => 24],
            ['name' => 'بوحمدان', 'wilaya_id' => 24],
            ['name' => 'حمام دباغ', 'wilaya_id' => 24],
            ['name' => 'الركنية', 'wilaya_id' => 24],
            ['name' => 'الدهوارة', 'wilaya_id' => 24],
            ['name' => 'حمام النبايل', 'wilaya_id' => 24],
            ['name' => 'قالمة', 'wilaya_id' => 24],
            ['name' => 'بومهرة أحمد', 'wilaya_id' => 24],
            ['name' => 'عين بن بيضاء', 'wilaya_id' => 24],
            ['name' => 'بوشقوف', 'wilaya_id' => 24],
            ['name' => 'مجاز الصفاء', 'wilaya_id' => 24],
            ['name' => 'وادي فراغة', 'wilaya_id' => 24],
            ['name' => 'بوعاتي محمود', 'wilaya_id' => 24],
            ['name' => 'الفجوج', 'wilaya_id' => 24],
            ['name' => 'هيليوبوليس', 'wilaya_id' => 24],
            ['name' => 'مجاز عمار', 'wilaya_id' => 24],
            ['name' => 'هواري بومدين', 'wilaya_id' => 24],
            ['name' => 'رأس العقبة', 'wilaya_id' => 24],
            ['name' => 'سلاوة عنونة', 'wilaya_id' => 24],
            ['name' => 'جبالة الخميسي', 'wilaya_id' => 24],
            ['name' => 'برج صباط', 'wilaya_id' => 24],
            ['name' => 'وادي الزناتي', 'wilaya_id' => 24],
            ['name' => 'عين رقادة', 'wilaya_id' => 24],
            ['name' => 'عين العربي', 'wilaya_id' => 24],
            ['name' => 'عين مخلوف', 'wilaya_id' => 24],
            ['name' => 'تاملوكة', 'wilaya_id' => 24],
            ['name' => 'عين صندل', 'wilaya_id' => 24],
            ['name' => 'بوحشانة', 'wilaya_id' => 24],
            ['name' => 'لخزارة', 'wilaya_id' => 24],
            ['name' => 'بلخير', 'wilaya_id' => 24],
            ['name' => 'بني مزلين', 'wilaya_id' => 24],
            ['name' => 'قلعة بوصبع', 'wilaya_id' => 24],
            ['name' => 'وادي الشحم', 'wilaya_id' => 24],
            ['name' => 'بن جراح', 'wilaya_id' => 24],
            ['name' => 'ديدوش مراد', 'wilaya_id' => 25],
            ['name' => 'حامة بوزيان', 'wilaya_id' => 25],
            ['name' => 'بني حميدان', 'wilaya_id' => 25],
            ['name' => 'زيغود يوسف', 'wilaya_id' => 25],
            ['name' => 'عين السمارة', 'wilaya_id' => 25],
            ['name' => 'الخروب', 'wilaya_id' => 25],
            ['name' => 'أولاد رحمون', 'wilaya_id' => 25],
            ['name' => 'عين عبيد', 'wilaya_id' => 25],
            ['name' => 'أبن باديس الهرية', 'wilaya_id' => 25],
            ['name' => 'ابن زياد', 'wilaya_id' => 25],
            ['name' => 'بوجريو مسعود', 'wilaya_id' => 25],
            ['name' => 'قسنطينة', 'wilaya_id' => 25],
            ['name' => 'أولاد هلال', 'wilaya_id' => 26],
            ['name' => 'السواقي', 'wilaya_id' => 26],
            ['name' => 'قصر البخاري', 'wilaya_id' => 26],
            ['name' => 'مفاتحة', 'wilaya_id' => 26],
            ['name' => 'السانق', 'wilaya_id' => 26],
            ['name' => 'العزيزية', 'wilaya_id' => 26],
            ['name' => 'مغراوة', 'wilaya_id' => 26],
            ['name' => 'ميهوب', 'wilaya_id' => 26],
            ['name' => 'بوعيش', 'wilaya_id' => 26],
            ['name' => 'بوغزول', 'wilaya_id' => 26],
            ['name' => 'الشهبونية', 'wilaya_id' => 26],
            ['name' => 'حناشة', 'wilaya_id' => 26],
            ['name' => 'عوامري', 'wilaya_id' => 26],
            ['name' => 'وادي حربيل', 'wilaya_id' => 26],
            ['name' => 'بني سليمان', 'wilaya_id' => 26],
            ['name' => 'بوعيشون', 'wilaya_id' => 26],
            ['name' => 'أولاد بوعشرة', 'wilaya_id' => 26],
            ['name' => 'سي المحجوب', 'wilaya_id' => 26],
            ['name' => 'بوسكن', 'wilaya_id' => 26],
            ['name' => 'سيدي الربيع', 'wilaya_id' => 26],
            ['name' => 'البرواقية', 'wilaya_id' => 26],
            ['name' => 'أولاد دايد', 'wilaya_id' => 26],
            ['name' => 'الربعية', 'wilaya_id' => 26],
            ['name' => 'مجبر', 'wilaya_id' => 26],
            ['name' => 'ثلاث دوائر', 'wilaya_id' => 26],
            ['name' => 'الزبيرية', 'wilaya_id' => 26],
            ['name' => 'العيساوية', 'wilaya_id' => 26],
            ['name' => 'الحوضان', 'wilaya_id' => 26],
            ['name' => 'مزغنة', 'wilaya_id' => 26],
            ['name' => 'تابلاط', 'wilaya_id' => 26],
            ['name' => 'بوغار', 'wilaya_id' => 26],
            ['name' => 'سغوان', 'wilaya_id' => 26],
            ['name' => 'ذراع السمار', 'wilaya_id' => 26],
            ['name' => 'المدية', 'wilaya_id' => 26],
            ['name' => 'تمسقيدة', 'wilaya_id' => 26],
            ['name' => 'بن شكاو', 'wilaya_id' => 26],
            ['name' => 'الحمدانية', 'wilaya_id' => 26],
            ['name' => 'وزرة', 'wilaya_id' => 26],
            ['name' => 'تيزي مهدي', 'wilaya_id' => 26],
            ['name' => 'عين بوسيف', 'wilaya_id' => 26],
            ['name' => 'العوينات', 'wilaya_id' => 26],
            ['name' => 'الكاف الاخضر', 'wilaya_id' => 26],
            ['name' => 'أولاد امعرف', 'wilaya_id' => 26],
            ['name' => 'سيدي دامد', 'wilaya_id' => 26],
            ['name' => 'بعطة', 'wilaya_id' => 26],
            ['name' => 'العمارية', 'wilaya_id' => 26],
            ['name' => 'أولاد إبراهيم', 'wilaya_id' => 26],
            ['name' => 'بئر بن عابد', 'wilaya_id' => 26],
            ['name' => 'القلب الكبير', 'wilaya_id' => 26],
            ['name' => 'سدراية', 'wilaya_id' => 26],
            ['name' => 'عين اقصير', 'wilaya_id' => 26],
            ['name' => 'شلالة العذاورة', 'wilaya_id' => 26],
            ['name' => 'شنيقل', 'wilaya_id' => 26],
            ['name' => 'تفراوت', 'wilaya_id' => 26],
            ['name' => 'بوشراحيل', 'wilaya_id' => 26],
            ['name' => 'خمس جوامع', 'wilaya_id' => 26],
            ['name' => 'سيدي نعمان', 'wilaya_id' => 26],
            ['name' => 'عزيز', 'wilaya_id' => 26],
            ['name' => 'دراق', 'wilaya_id' => 26],
            ['name' => 'أم الجليل', 'wilaya_id' => 26],
            ['name' => 'جواب', 'wilaya_id' => 26],
            ['name' => 'سيدي زهار', 'wilaya_id' => 26],
            ['name' => 'سيدي زيان', 'wilaya_id' => 26],
            ['name' => 'أولاد عنتر', 'wilaya_id' => 26],
            ['name' => 'فرناقة', 'wilaya_id' => 27],
            ['name' => 'وادي الخير', 'wilaya_id' => 27],
            ['name' => 'الحسيان (بني ياحي', 'wilaya_id' => 27],
            ['name' => 'حاسي ماماش', 'wilaya_id' => 27],
            ['name' => 'مزغران', 'wilaya_id' => 27],
            ['name' => 'ستيدية', 'wilaya_id' => 27],
            ['name' => 'عين تادلس', 'wilaya_id' => 27],
            ['name' => 'سيدي بلعطار', 'wilaya_id' => 27],
            ['name' => 'سور', 'wilaya_id' => 27],
            ['name' => 'عين بودينار', 'wilaya_id' => 27],
            ['name' => 'خير الدين', 'wilaya_id' => 27],
            ['name' => 'صيادة', 'wilaya_id' => 27],
            ['name' => 'سيدي علي', 'wilaya_id' => 27],
            ['name' => 'تزقايت', 'wilaya_id' => 27],
            ['name' => 'بن عبد المالك رمضان', 'wilaya_id' => 27],
            ['name' => 'مستغانم', 'wilaya_id' => 27],
            ['name' => 'حجاج', 'wilaya_id' => 27],
            ['name' => 'سيدي لخضر', 'wilaya_id' => 27],
            ['name' => 'عشعاشة', 'wilaya_id' => 27],
            ['name' => 'خضرة', 'wilaya_id' => 27],
            ['name' => 'نكمارية', 'wilaya_id' => 27],
            ['name' => 'أولاد بوغالم', 'wilaya_id' => 27],
            ['name' => 'بوقيراط', 'wilaya_id' => 27],
            ['name' => 'صفصاف', 'wilaya_id' => 27],
            ['name' => 'سيرات', 'wilaya_id' => 27],
            ['name' => 'السوافلية', 'wilaya_id' => 27],
            ['name' => 'عين سيدي الشريف', 'wilaya_id' => 27],
            ['name' => 'منصورة', 'wilaya_id' => 27],
            ['name' => 'ماسرة', 'wilaya_id' => 27],
            ['name' => 'الطواهرية', 'wilaya_id' => 27],
            ['name' => 'عين نويسي', 'wilaya_id' => 27],
            ['name' => 'أولاد مع الله', 'wilaya_id' => 27],
            ['name' => 'شلال', 'wilaya_id' => 28],
            ['name' => 'أولاد ماضي', 'wilaya_id' => 28],
            ['name' => 'خطوطي سد الجير', 'wilaya_id' => 28],
            ['name' => 'بلعايبة', 'wilaya_id' => 28],
            ['name' => 'برهوم', 'wilaya_id' => 28],
            ['name' => 'دهاهنة', 'wilaya_id' => 28],
            ['name' => 'مقرة', 'wilaya_id' => 28],
            ['name' => 'بني يلمان', 'wilaya_id' => 28],
            ['name' => 'بوطي السايح', 'wilaya_id' => 28],
            ['name' => 'سيدي عيسى', 'wilaya_id' => 28],
            ['name' => 'عين الحجل', 'wilaya_id' => 28],
            ['name' => 'سيدي هجرس', 'wilaya_id' => 28],
            ['name' => 'بوسعادة', 'wilaya_id' => 28],
            ['name' => 'الهامل', 'wilaya_id' => 28],
            ['name' => 'ولتام', 'wilaya_id' => 28],
            ['name' => 'بن زوه', 'wilaya_id' => 28],
            ['name' => 'أولاد سيدي ابراهيم', 'wilaya_id' => 28],
            ['name' => 'سيدي عامر', 'wilaya_id' => 28],
            ['name' => 'تامسة', 'wilaya_id' => 28],
            ['name' => 'بن سرور', 'wilaya_id' => 28],
            ['name' => 'محمد بوضياف', 'wilaya_id' => 28],
            ['name' => 'أولاد سليمان', 'wilaya_id' => 28],
            ['name' => 'زرزور', 'wilaya_id' => 28],
            ['name' => 'عين الملح', 'wilaya_id' => 28],
            ['name' => 'عين فارس', 'wilaya_id' => 28],
            ['name' => 'عين الريش', 'wilaya_id' => 28],
            ['name' => 'بئر فضة', 'wilaya_id' => 28],
            ['name' => 'سيدي امحمد', 'wilaya_id' => 28],
            ['name' => 'امجدل', 'wilaya_id' => 28],
            ['name' => 'مناعة', 'wilaya_id' => 28],
            ['name' => 'جبل مساعد', 'wilaya_id' => 28],
            ['name' => 'سليم', 'wilaya_id' => 28],
            ['name' => 'المسيلة', 'wilaya_id' => 28],
            ['name' => 'حمام الضلعة', 'wilaya_id' => 28],
            ['name' => 'ونوغة', 'wilaya_id' => 28],
            ['name' => 'أولاد منصور', 'wilaya_id' => 28],
            ['name' => 'تارمونت', 'wilaya_id' => 28],
            ['name' => 'المعاضيد', 'wilaya_id' => 28],
            ['name' => 'المطارفة', 'wilaya_id' => 28],
            ['name' => 'معاريف', 'wilaya_id' => 28],
            ['name' => 'أولاد دراج', 'wilaya_id' => 28],
            ['name' => 'السوامع', 'wilaya_id' => 28],
            ['name' => 'الحوامد', 'wilaya_id' => 28],
            ['name' => 'خبانة', 'wilaya_id' => 28],
            ['name' => 'مسيف', 'wilaya_id' => 28],
            ['name' => 'عين الخضراء', 'wilaya_id' => 28],
            ['name' => 'أولاد عدي لقبالة', 'wilaya_id' => 28],
            ['name' => 'وادي الأبطال', 'wilaya_id' => 29],
            ['name' => 'سيدي عبد المومن', 'wilaya_id' => 29],
            ['name' => 'سجرارة', 'wilaya_id' => 29],
            ['name' => 'المحمدية', 'wilaya_id' => 29],
            ['name' => 'تيغنيف', 'wilaya_id' => 29],
            ['name' => 'مقطع الدوز', 'wilaya_id' => 29],
            ['name' => 'فراقيق', 'wilaya_id' => 29],
            ['name' => 'الغمري', 'wilaya_id' => 29],
            ['name' => 'زهانة', 'wilaya_id' => 29],
            ['name' => 'القعدة', 'wilaya_id' => 29],
            ['name' => 'رأس عين عميروش', 'wilaya_id' => 29],
            ['name' => 'عقاز', 'wilaya_id' => 29],
            ['name' => 'العلايمية', 'wilaya_id' => 29],
            ['name' => 'سيق', 'wilaya_id' => 29],
            ['name' => 'الشرفاء', 'wilaya_id' => 29],
            ['name' => 'بوهني', 'wilaya_id' => 29],
            ['name' => 'المأمونية', 'wilaya_id' => 29],
            ['name' => 'القطنة', 'wilaya_id' => 29],
            ['name' => 'عين فارس', 'wilaya_id' => 29],
            ['name' => 'غروس', 'wilaya_id' => 29],
            ['name' => 'بنيان', 'wilaya_id' => 29],
            ['name' => 'عوف', 'wilaya_id' => 29],
            ['name' => 'قرجوم', 'wilaya_id' => 29],
            ['name' => 'عين أفرص', 'wilaya_id' => 29],
            ['name' => 'عين فكان', 'wilaya_id' => 29],
            ['name' => 'خلوية', 'wilaya_id' => 29],
            ['name' => 'المنور', 'wilaya_id' => 29],
            ['name' => 'البرج', 'wilaya_id' => 29],
            ['name' => 'سيدي بوسعيد', 'wilaya_id' => 29],
            ['name' => 'المطمور', 'wilaya_id' => 29],
            ['name' => 'سيدي قادة', 'wilaya_id' => 29],
            ['name' => 'ماقضة', 'wilaya_id' => 29],
            ['name' => 'معسكر', 'wilaya_id' => 29],
            ['name' => 'بوحنيفية', 'wilaya_id' => 29],
            ['name' => 'غريس', 'wilaya_id' => 29],
            ['name' => 'حسين', 'wilaya_id' => 29],
            ['name' => 'القرط', 'wilaya_id' => 29],
            ['name' => 'فروحة', 'wilaya_id' => 29],
            ['name' => 'تيزي', 'wilaya_id' => 29],
            ['name' => 'السهايلية', 'wilaya_id' => 29],
            ['name' => 'ماوسة', 'wilaya_id' => 29],
            ['name' => 'سيدي عبد الجبار', 'wilaya_id' => 29],
            ['name' => 'الحشم', 'wilaya_id' => 29],
            ['name' => 'نسمط', 'wilaya_id' => 29],
            ['name' => 'زلامطة', 'wilaya_id' => 29],
            ['name' => 'عين فراح', 'wilaya_id' => 29],
            ['name' => 'وادي التاغية', 'wilaya_id' => 29],
            ['name' => 'ورقلة', 'wilaya_id' => 30],
            ['name' => 'حاسي مسعود', 'wilaya_id' => 30],
            ['name' => 'عين البيضاء', 'wilaya_id' => 30],
            ['name' => 'حاسي بن عبد الله', 'wilaya_id' => 30],
            ['name' => 'سيدي خويلد', 'wilaya_id' => 30],
            ['name' => 'البرمة', 'wilaya_id' => 30],
            ['name' => 'الرويسات', 'wilaya_id' => 30],
            ['name' => 'انقوسة', 'wilaya_id' => 30],
            ['name' => 'سيدي الشحمي', 'wilaya_id' => 31],
            ['name' => 'حاسي مفسوخ', 'wilaya_id' => 31],
            ['name' => 'بئر الجير', 'wilaya_id' => 31],
            ['name' => 'حاسي بن عقبة', 'wilaya_id' => 31],
            ['name' => 'قديل', 'wilaya_id' => 31],
            ['name' => 'حاسي بونيف', 'wilaya_id' => 31],
            ['name' => 'الكرمة', 'wilaya_id' => 31],
            ['name' => 'السانية', 'wilaya_id' => 31],
            ['name' => 'بن فريحة', 'wilaya_id' => 31],
            ['name' => 'أرزيو', 'wilaya_id' => 31],
            ['name' => 'سيدي بن يبقى', 'wilaya_id' => 31],
            ['name' => 'عين البية', 'wilaya_id' => 31],
            ['name' => 'بطيوة', 'wilaya_id' => 31],
            ['name' => 'مرسى الحجاج', 'wilaya_id' => 31],
            ['name' => 'عين الترك', 'wilaya_id' => 31],
            ['name' => 'وهران', 'wilaya_id' => 31],
            ['name' => 'العنصر', 'wilaya_id' => 31],
            ['name' => 'المرسى الكبير', 'wilaya_id' => 31],
            ['name' => 'بوفاتيس', 'wilaya_id' => 31],
            ['name' => 'البراية', 'wilaya_id' => 31],
            ['name' => 'وادي تليلات', 'wilaya_id' => 31],
            ['name' => 'عين الكرمة', 'wilaya_id' => 31],
            ['name' => 'بوتليليس', 'wilaya_id' => 31],
            ['name' => 'مسرغين', 'wilaya_id' => 31],
            ['name' => 'بوسفر', 'wilaya_id' => 31],
            ['name' => 'طفراوي', 'wilaya_id' => 31],
            ['name' => 'عين العراك', 'wilaya_id' => 32],
            ['name' => 'كراكدة', 'wilaya_id' => 32],
            ['name' => 'سيدي سليمان', 'wilaya_id' => 32],
            ['name' => 'سيدي عامر', 'wilaya_id' => 32],
            ['name' => 'بوعلام', 'wilaya_id' => 32],
            ['name' => 'البنود', 'wilaya_id' => 32],
            ['name' => 'بوقطب', 'wilaya_id' => 32],
            ['name' => 'الخيثر', 'wilaya_id' => 32],
            ['name' => 'توسمولين', 'wilaya_id' => 32],
            ['name' => 'سيدي طيفور', 'wilaya_id' => 32],
            ['name' => 'ستيتن', 'wilaya_id' => 32],
            ['name' => 'البيض', 'wilaya_id' => 32],
            ['name' => 'رقاصة', 'wilaya_id' => 32],
            ['name' => 'المحرة', 'wilaya_id' => 32],
            ['name' => 'الكاف الأحمر', 'wilaya_id' => 32],
            ['name' => 'بريزينة', 'wilaya_id' => 32],
            ['name' => 'الغاسول', 'wilaya_id' => 32],
            ['name' => 'الأبيض سيدي الشيخ', 'wilaya_id' => 32],
            ['name' => 'بوسمغون', 'wilaya_id' => 32],
            ['name' => 'الشقيق', 'wilaya_id' => 32],
            ['name' => 'شلالة', 'wilaya_id' => 32],
            ['name' => 'اربوات', 'wilaya_id' => 32],
            ['name' => 'برج عمر إدريس', 'wilaya_id' => 33],
            ['name' => 'دبداب', 'wilaya_id' => 33],
            ['name' => 'إن أمناس', 'wilaya_id' => 33],
            ['name' => 'إيليزي', 'wilaya_id' => 33],
            ['name' => 'الحمادية', 'wilaya_id' => 34],
            ['name' => 'أولاد سيدي ابراهيم', 'wilaya_id' => 34],
            ['name' => 'عين تاغروت', 'wilaya_id' => 34],
            ['name' => 'تيكستار', 'wilaya_id' => 34],
            ['name' => 'بليمور', 'wilaya_id' => 34],
            ['name' => 'العناصر', 'wilaya_id' => 34],
            ['name' => 'غيلاسة', 'wilaya_id' => 34],
            ['name' => 'تقلعيت', 'wilaya_id' => 34],
            ['name' => 'برج الغدير', 'wilaya_id' => 34],
            ['name' => 'العش', 'wilaya_id' => 34],
            ['name' => 'سيدي أمبارك', 'wilaya_id' => 34],
            ['name' => 'خليل', 'wilaya_id' => 34],
            ['name' => 'بئر قاصد علي', 'wilaya_id' => 34],
            ['name' => 'تفرق', 'wilaya_id' => 34],
            ['name' => 'الماين', 'wilaya_id' => 34],
            ['name' => 'جعافرة', 'wilaya_id' => 34],
            ['name' => 'القلة', 'wilaya_id' => 34],
            ['name' => 'ثنية النصر', 'wilaya_id' => 34],
            ['name' => 'المهير', 'wilaya_id' => 34],
            ['name' => 'القصور', 'wilaya_id' => 34],
            ['name' => 'المنصورة', 'wilaya_id' => 34],
            ['name' => 'حرازة', 'wilaya_id' => 34],
            ['name' => 'الرابطة', 'wilaya_id' => 34],
            ['name' => 'الياشير', 'wilaya_id' => 34],
            ['name' => 'حسناوة', 'wilaya_id' => 34],
            ['name' => 'مجانة', 'wilaya_id' => 34],
            ['name' => 'عين تسرة', 'wilaya_id' => 34],
            ['name' => 'أولاد أبراهم', 'wilaya_id' => 34],
            ['name' => 'رأس الوادي', 'wilaya_id' => 34],
            ['name' => 'برج زمورة', 'wilaya_id' => 34],
            ['name' => 'أولاد دحمان', 'wilaya_id' => 34],
            ['name' => 'تسامرت', 'wilaya_id' => 34],
            ['name' => 'برج بوعريرج', 'wilaya_id' => 34],
            ['name' => 'بن داود', 'wilaya_id' => 34],
            ['name' => 'الخروبة', 'wilaya_id' => 35],
            ['name' => 'دلس', 'wilaya_id' => 35],
            ['name' => 'بن شود', 'wilaya_id' => 35],
            ['name' => 'أعفير', 'wilaya_id' => 35],
            ['name' => 'الثنية', 'wilaya_id' => 35],
            ['name' => 'بني عمران', 'wilaya_id' => 35],
            ['name' => 'خميس الخشنة', 'wilaya_id' => 35],
            ['name' => 'عمال', 'wilaya_id' => 35],
            ['name' => 'تيمزريت', 'wilaya_id' => 35],
            ['name' => 'زموري', 'wilaya_id' => 35],
            ['name' => 'الاربعطاش', 'wilaya_id' => 35],
            ['name' => 'يسر', 'wilaya_id' => 35],
            ['name' => 'شعبة العامر', 'wilaya_id' => 35],
            ['name' => 'أولاد عيسى', 'wilaya_id' => 35],
            ['name' => 'الناصرية', 'wilaya_id' => 35],
            ['name' => 'بوزقزة قدارة', 'wilaya_id' => 35],
            ['name' => 'سوق الحد', 'wilaya_id' => 35],
            ['name' => 'سيدي داود', 'wilaya_id' => 35],
            ['name' => 'بغلية', 'wilaya_id' => 35],
            ['name' => 'لقاطة', 'wilaya_id' => 35],
            ['name' => 'جنات', 'wilaya_id' => 35],
            ['name' => 'تيجلابين', 'wilaya_id' => 35],
            ['name' => 'سي مصطفى', 'wilaya_id' => 35],
            ['name' => 'أولاد هداج', 'wilaya_id' => 35],
            ['name' => 'أولاد موسى', 'wilaya_id' => 35],
            ['name' => 'بومرداس', 'wilaya_id' => 35],
            ['name' => 'قورصو', 'wilaya_id' => 35],
            ['name' => 'برج منايل', 'wilaya_id' => 35],
            ['name' => 'بودواو', 'wilaya_id' => 35],
            ['name' => 'بودواو البحري', 'wilaya_id' => 35],
            ['name' => 'تاورقة', 'wilaya_id' => 35],
            ['name' => 'حمادي', 'wilaya_id' => 35],
            ['name' => 'عين العسل', 'wilaya_id' => 36],
            ['name' => 'بوقوس', 'wilaya_id' => 36],
            ['name' => 'الطارف', 'wilaya_id' => 36],
            ['name' => 'الزيتونة', 'wilaya_id' => 36],
            ['name' => 'البسباس', 'wilaya_id' => 36],
            ['name' => 'عين الكرمة', 'wilaya_id' => 36],
            ['name' => 'بوحجار', 'wilaya_id' => 36],
            ['name' => 'حمام بني صالح', 'wilaya_id' => 36],
            ['name' => 'وادي الزيتون', 'wilaya_id' => 36],
            ['name' => 'بن مهيدي', 'wilaya_id' => 36],
            ['name' => 'بريحان', 'wilaya_id' => 36],
            ['name' => 'شبيطة مختار', 'wilaya_id' => 36],
            ['name' => 'الشط', 'wilaya_id' => 36],
            ['name' => 'العيون', 'wilaya_id' => 36],
            ['name' => 'القالة', 'wilaya_id' => 36],
            ['name' => 'السوارخ', 'wilaya_id' => 36],
            ['name' => 'زريزر', 'wilaya_id' => 36],
            ['name' => 'بوثلجة', 'wilaya_id' => 36],
            ['name' => 'الشافية', 'wilaya_id' => 36],
            ['name' => 'بحيرة الطيور', 'wilaya_id' => 36],
            ['name' => 'شحاني', 'wilaya_id' => 36],
            ['name' => 'رمل السوق', 'wilaya_id' => 36],
            ['name' => 'عصفور', 'wilaya_id' => 36],
            ['name' => 'الذرعـان', 'wilaya_id' => 36],
            ['name' => 'تندوف', 'wilaya_id' => 37],
            ['name' => 'أم العسل', 'wilaya_id' => 37],
            ['name' => 'خميستي', 'wilaya_id' => 38],
            ['name' => 'ثنية الاحد', 'wilaya_id' => 38],
            ['name' => 'أولاد بسام', 'wilaya_id' => 38],
            ['name' => 'سيدي بوتوشنت', 'wilaya_id' => 38],
            ['name' => 'تيسمسيلت', 'wilaya_id' => 38],
            ['name' => 'سيدي العنتري', 'wilaya_id' => 38],
            ['name' => 'بني شعيب', 'wilaya_id' => 38],
            ['name' => 'بني لحسن', 'wilaya_id' => 38],
            ['name' => 'سيدي عابد', 'wilaya_id' => 38],
            ['name' => 'سيدي سليمان', 'wilaya_id' => 38],
            ['name' => 'بوقائد', 'wilaya_id' => 38],
            ['name' => 'الأربعاء', 'wilaya_id' => 38],
            ['name' => 'الأزهرية', 'wilaya_id' => 38],
            ['name' => 'لرجام', 'wilaya_id' => 38],
            ['name' => 'الملعب', 'wilaya_id' => 38],
            ['name' => 'العيون', 'wilaya_id' => 38],
            ['name' => 'تملاحت', 'wilaya_id' => 38],
            ['name' => 'اليوسفية', 'wilaya_id' => 38],
            ['name' => 'برج الأمير عبد القادر', 'wilaya_id' => 38],
            ['name' => 'عماري', 'wilaya_id' => 38],
            ['name' => 'المعاصم', 'wilaya_id' => 38],
            ['name' => 'برج بونعامة', 'wilaya_id' => 38],
            ['name' => 'دوار الماء', 'wilaya_id' => 39],
            ['name' => 'العقلة', 'wilaya_id' => 39],
            ['name' => 'المقرن', 'wilaya_id' => 39],
            ['name' => 'سيدي عون', 'wilaya_id' => 39],
            ['name' => 'اميه وانسة', 'wilaya_id' => 39],
            ['name' => 'كوينين', 'wilaya_id' => 39],
            ['name' => 'البياضة', 'wilaya_id' => 39],
            ['name' => 'النخلة', 'wilaya_id' => 39],
            ['name' => 'الرباح', 'wilaya_id' => 39],
            ['name' => 'قمار', 'wilaya_id' => 39],
            ['name' => 'بن  قشة', 'wilaya_id' => 39],
            ['name' => 'ورماس', 'wilaya_id' => 39],
            ['name' => 'تغزوت', 'wilaya_id' => 39],
            ['name' => 'الحمراية', 'wilaya_id' => 39],
            ['name' => 'الرقيبة', 'wilaya_id' => 39],
            ['name' => 'الدبيلة', 'wilaya_id' => 39],
            ['name' => 'حساني عبد الكريم', 'wilaya_id' => 39],
            ['name' => 'حاسي خليفة', 'wilaya_id' => 39],
            ['name' => 'الطريفاوي', 'wilaya_id' => 39],
            ['name' => 'الطالب العربي', 'wilaya_id' => 39],
            ['name' => 'وادي العلندة', 'wilaya_id' => 39],
            ['name' => 'الوادي', 'wilaya_id' => 39],
            ['name' => 'خيران', 'wilaya_id' => 40],
            ['name' => 'بابار', 'wilaya_id' => 40],
            ['name' => 'المحمل', 'wilaya_id' => 40],
            ['name' => 'أولاد رشاش', 'wilaya_id' => 40],
            ['name' => 'جلال', 'wilaya_id' => 40],
            ['name' => 'يابوس', 'wilaya_id' => 40],
            ['name' => 'خنشلة', 'wilaya_id' => 40],
            ['name' => 'قايس', 'wilaya_id' => 40],
            ['name' => 'شلية', 'wilaya_id' => 40],
            ['name' => 'الرميلة', 'wilaya_id' => 40],
            ['name' => 'تاوزيانت', 'wilaya_id' => 40],
            ['name' => 'بغاي', 'wilaya_id' => 40],
            ['name' => 'الحامة', 'wilaya_id' => 40],
            ['name' => 'انسيغة', 'wilaya_id' => 40],
            ['name' => 'طامزة', 'wilaya_id' => 40],
            ['name' => 'عين الطويلة', 'wilaya_id' => 40],
            ['name' => 'متوسة', 'wilaya_id' => 40],
            ['name' => 'بوحمامة', 'wilaya_id' => 40],
            ['name' => 'الولجة', 'wilaya_id' => 40],
            ['name' => 'مصارة', 'wilaya_id' => 40],
            ['name' => 'ششار', 'wilaya_id' => 40],
            ['name' => 'سوق أهراس', 'wilaya_id' => 41],
            ['name' => 'عين سلطان', 'wilaya_id' => 41],
            ['name' => 'سدراتة', 'wilaya_id' => 41],
            ['name' => 'الحنانشة', 'wilaya_id' => 41],
            ['name' => 'المشروحة', 'wilaya_id' => 41],
            ['name' => 'عين الزانة', 'wilaya_id' => 41],
            ['name' => 'أولاد إدريس', 'wilaya_id' => 41],
            ['name' => 'ترقالت', 'wilaya_id' => 41],
            ['name' => 'أم العظايم', 'wilaya_id' => 41],
            ['name' => 'وادي الكبريت', 'wilaya_id' => 41],
            ['name' => 'تيفاش', 'wilaya_id' => 41],
            ['name' => 'الراقوبة', 'wilaya_id' => 41],
            ['name' => 'الدريعة', 'wilaya_id' => 41],
            ['name' => 'تاورة', 'wilaya_id' => 41],
            ['name' => 'الزعرورية', 'wilaya_id' => 41],
            ['name' => 'الحدادة', 'wilaya_id' => 41],
            ['name' => 'الخضارة', 'wilaya_id' => 41],
            ['name' => 'أولاد مومن', 'wilaya_id' => 41],
            ['name' => 'المراهنة', 'wilaya_id' => 41],
            ['name' => 'ويلان', 'wilaya_id' => 41],
            ['name' => 'سيدي فرج', 'wilaya_id' => 41],
            ['name' => 'بئر بوحوش', 'wilaya_id' => 41],
            ['name' => 'سافل الويدان', 'wilaya_id' => 41],
            ['name' => 'خميسة', 'wilaya_id' => 41],
            ['name' => 'مداوروش', 'wilaya_id' => 41],
            ['name' => 'الزوابي', 'wilaya_id' => 41],
            ['name' => 'حجوط', 'wilaya_id' => 42],
            ['name' => 'مراد', 'wilaya_id' => 42],
            ['name' => 'مناصر', 'wilaya_id' => 42],
            ['name' => 'أغبال', 'wilaya_id' => 42],
            ['name' => 'الناظور', 'wilaya_id' => 42],
            ['name' => 'سيدي عامر', 'wilaya_id' => 42],
            ['name' => 'قوراية', 'wilaya_id' => 42],
            ['name' => 'مسلمون', 'wilaya_id' => 42],
            ['name' => 'شرشال', 'wilaya_id' => 42],
            ['name' => 'حجرة النص', 'wilaya_id' => 42],
            ['name' => 'سيدي غيلاس', 'wilaya_id' => 42],
            ['name' => 'الداموس', 'wilaya_id' => 42],
            ['name' => 'الأرهاط', 'wilaya_id' => 42],
            ['name' => 'فوكة', 'wilaya_id' => 42],
            ['name' => 'عين تاقورايت', 'wilaya_id' => 42],
            ['name' => 'بوهارون', 'wilaya_id' => 42],
            ['name' => 'بواسماعيل', 'wilaya_id' => 42],
            ['name' => 'خميستي', 'wilaya_id' => 42],
            ['name' => 'أحمر العين', 'wilaya_id' => 42],
            ['name' => 'بورقيقة', 'wilaya_id' => 42],
            ['name' => 'دواودة', 'wilaya_id' => 42],
            ['name' => 'سيدي راشد', 'wilaya_id' => 42],
            ['name' => 'الحطاطبة', 'wilaya_id' => 42],
            ['name' => 'الشعيبة', 'wilaya_id' => 42],
            ['name' => 'القليعة', 'wilaya_id' => 42],
            ['name' => 'سيدي سميان', 'wilaya_id' => 42],
            ['name' => 'تيبازة', 'wilaya_id' => 42],
            ['name' => 'بني ميلك', 'wilaya_id' => 42],
            ['name' => 'مشيرة', 'wilaya_id' => 43],
            ['name' => 'العياضي برباس', 'wilaya_id' => 43],
            ['name' => 'عين البيضاء أحريش', 'wilaya_id' => 43],
            ['name' => 'تسالة لمطاعي', 'wilaya_id' => 43],
            ['name' => 'ترعي باينان', 'wilaya_id' => 43],
            ['name' => 'اعميرة اراس', 'wilaya_id' => 43],
            ['name' => 'تسدان حدادة', 'wilaya_id' => 43],
            ['name' => 'مينار زارزة', 'wilaya_id' => 43],
            ['name' => 'سيدي مروان', 'wilaya_id' => 43],
            ['name' => 'الشيقارة', 'wilaya_id' => 43],
            ['name' => 'حمالة', 'wilaya_id' => 43],
            ['name' => 'القرارم قوقة', 'wilaya_id' => 43],
            ['name' => 'تيبرقنت', 'wilaya_id' => 43],
            ['name' => 'الرواشد', 'wilaya_id' => 43],
            ['name' => 'دراحي بوصلاح', 'wilaya_id' => 43],
            ['name' => 'زغاية', 'wilaya_id' => 43],
            ['name' => 'وادي النجاء', 'wilaya_id' => 43],
            ['name' => 'أحمد راشدي', 'wilaya_id' => 43],
            ['name' => 'تاجنانت', 'wilaya_id' => 43],
            ['name' => 'عين الملوك', 'wilaya_id' => 43],
            ['name' => 'أولاد اخلوف', 'wilaya_id' => 43],
            ['name' => 'بن يحي عبد الرحمن', 'wilaya_id' => 43],
            ['name' => 'التلاغمة', 'wilaya_id' => 43],
            ['name' => 'وادي سقان', 'wilaya_id' => 43],
            ['name' => 'وادي العثمانية', 'wilaya_id' => 43],
            ['name' => 'عين التين', 'wilaya_id' => 43],
            ['name' => 'شلغوم العيد', 'wilaya_id' => 43],
            ['name' => 'يحي بني قشة', 'wilaya_id' => 43],
            ['name' => 'فرجيوة', 'wilaya_id' => 43],
            ['name' => 'سيدي خليفة', 'wilaya_id' => 43],
            ['name' => 'ميلة', 'wilaya_id' => 43],
            ['name' => 'بوحاتم', 'wilaya_id' => 43],
            ['name' => 'خميس مليانة', 'wilaya_id' => 44],
            ['name' => 'سيدي الأخضر', 'wilaya_id' => 44],
            ['name' => 'عين البنيان', 'wilaya_id' => 44],
            ['name' => 'عين التركي', 'wilaya_id' => 44],
            ['name' => 'حمام ريغة', 'wilaya_id' => 44],
            ['name' => 'بوراشد', 'wilaya_id' => 44],
            ['name' => 'الحسينية', 'wilaya_id' => 44],
            ['name' => 'جليدة', 'wilaya_id' => 44],
            ['name' => 'عريب', 'wilaya_id' => 44],
            ['name' => 'جمعة أولاد الشيخ', 'wilaya_id' => 44],
            ['name' => 'العامرة', 'wilaya_id' => 44],
            ['name' => 'العطاف', 'wilaya_id' => 44],
            ['name' => 'تبركانين', 'wilaya_id' => 44],
            ['name' => 'عين بويحيى', 'wilaya_id' => 44],
            ['name' => 'العبادية', 'wilaya_id' => 44],
            ['name' => 'تاشتة زقاغة', 'wilaya_id' => 44],
            ['name' => 'بربوش', 'wilaya_id' => 44],
            ['name' => 'جندل', 'wilaya_id' => 44],
            ['name' => 'بن علال', 'wilaya_id' => 44],
            ['name' => 'وادي الشرفاء', 'wilaya_id' => 44],
            ['name' => 'بومدفع', 'wilaya_id' => 44],
            ['name' => 'عين الاشياخ', 'wilaya_id' => 44],
            ['name' => 'عين السلطان', 'wilaya_id' => 44],
            ['name' => 'واد الجمعة', 'wilaya_id' => 44],
            ['name' => 'الماين', 'wilaya_id' => 44],
            ['name' => 'الروينة', 'wilaya_id' => 44],
            ['name' => 'زدين', 'wilaya_id' => 44],
            ['name' => 'بئر ولد خليفة', 'wilaya_id' => 44],
            ['name' => 'برج الأمير خالد', 'wilaya_id' => 44],
            ['name' => 'طارق بن زياد', 'wilaya_id' => 44],
            ['name' => 'بطحية', 'wilaya_id' => 44],
            ['name' => 'بلعاص', 'wilaya_id' => 44],
            ['name' => 'الحسانية', 'wilaya_id' => 44],
            ['name' => 'عين الدفلى', 'wilaya_id' => 44],
            ['name' => 'مليانة', 'wilaya_id' => 44],
            ['name' => 'المخاطرية', 'wilaya_id' => 44],
            ['name' => 'تيوت', 'wilaya_id' => 45],
            ['name' => 'مغرار', 'wilaya_id' => 45],
            ['name' => 'عسلة', 'wilaya_id' => 45],
            ['name' => 'القصدير', 'wilaya_id' => 45],
            ['name' => 'مكمن بن عمار', 'wilaya_id' => 45],
            ['name' => 'عين الصفراء', 'wilaya_id' => 45],
            ['name' => 'المشرية', 'wilaya_id' => 45],
            ['name' => 'البيوض', 'wilaya_id' => 45],
            ['name' => 'عين بن خليل', 'wilaya_id' => 45],
            ['name' => 'النعامة', 'wilaya_id' => 45],
            ['name' => 'جنين بورزق', 'wilaya_id' => 45],
            ['name' => 'سفيسيفة', 'wilaya_id' => 45],
            ['name' => 'سيدي بومدين', 'wilaya_id' => 46],
            ['name' => 'تامزورة', 'wilaya_id' => 46],
            ['name' => 'شعبة اللحم', 'wilaya_id' => 46],
            ['name' => 'المالح', 'wilaya_id' => 46],
            ['name' => 'أولاد الكيحل', 'wilaya_id' => 46],
            ['name' => 'شنتوف', 'wilaya_id' => 46],
            ['name' => 'تارقة', 'wilaya_id' => 46],
            ['name' => 'وادي الصباح', 'wilaya_id' => 46],
            ['name' => 'العامرية', 'wilaya_id' => 46],
            ['name' => 'حاسي الغلة', 'wilaya_id' => 46],
            ['name' => 'أولاد بوجمعة', 'wilaya_id' => 46],
            ['name' => 'أغلال', 'wilaya_id' => 46],
            ['name' => 'عين الكيحل', 'wilaya_id' => 46],
            ['name' => 'عين الطلبة', 'wilaya_id' => 46],
            ['name' => 'عقب الليل', 'wilaya_id' => 46],
            ['name' => 'بني صاف', 'wilaya_id' => 46],
            ['name' => 'الحساسنة', 'wilaya_id' => 46],
            ['name' => 'الأمير عبد القادر', 'wilaya_id' => 46],
            ['name' => 'سيدي صافي', 'wilaya_id' => 46],
            ['name' => 'ولهاصة الغرابة', 'wilaya_id' => 46],
            ['name' => 'سيدي ورياش', 'wilaya_id' => 46],
            ['name' => 'عين الأربعاء', 'wilaya_id' => 46],
            ['name' => 'المساعيد', 'wilaya_id' => 46],
            ['name' => 'وادي برقش', 'wilaya_id' => 46],
            ['name' => 'سيدي بن عدة', 'wilaya_id' => 46],
            ['name' => 'عين تموشنت', 'wilaya_id' => 46],
            ['name' => 'بوزجار', 'wilaya_id' => 46],
            ['name' => 'حمام بوحجر', 'wilaya_id' => 46],
            ['name' => 'ضاية بن ضحوة', 'wilaya_id' => 47],
            ['name' => 'المنصورة', 'wilaya_id' => 47],
            ['name' => 'العطف', 'wilaya_id' => 47],
            ['name' => 'بونورة', 'wilaya_id' => 47],
            ['name' => 'زلفانة', 'wilaya_id' => 47],
            ['name' => 'القرارة', 'wilaya_id' => 47],
            ['name' => 'سبسب', 'wilaya_id' => 47],
            ['name' => 'متليلي', 'wilaya_id' => 47],
            ['name' => 'بريان', 'wilaya_id' => 47],
            ['name' => 'غرداية', 'wilaya_id' => 47],
            ['name' => 'القطار', 'wilaya_id' => 48],
            ['name' => 'أولاد يعيش', 'wilaya_id' => 48],
            ['name' => 'بني درقن', 'wilaya_id' => 48],
            ['name' => 'دار بن عبد الله', 'wilaya_id' => 48],
            ['name' => 'زمورة', 'wilaya_id' => 48],
            ['name' => 'جديوية', 'wilaya_id' => 48],
            ['name' => 'حمري', 'wilaya_id' => 48],
            ['name' => 'بلعسل بوزقزة', 'wilaya_id' => 48],
            ['name' => 'المطمر', 'wilaya_id' => 48],
            ['name' => 'سيدي  خطاب', 'wilaya_id' => 48],
            ['name' => 'سيدي امحمد بن عودة', 'wilaya_id' => 48],
            ['name' => 'عين طارق', 'wilaya_id' => 48],
            ['name' => 'حد الشكالة', 'wilaya_id' => 48],
            ['name' => 'الولجة', 'wilaya_id' => 48],
            ['name' => 'مازونة', 'wilaya_id' => 48],
            ['name' => 'عين الرحمة', 'wilaya_id' => 48],
            ['name' => 'القلعة', 'wilaya_id' => 48],
            ['name' => 'سيدي سعادة', 'wilaya_id' => 48],
            ['name' => 'يلل', 'wilaya_id' => 48],
            ['name' => 'سوق الحد', 'wilaya_id' => 48],
            ['name' => 'منداس', 'wilaya_id' => 48],
            ['name' => 'وادي السلام', 'wilaya_id' => 48],
            ['name' => 'سيدي لزرق', 'wilaya_id' => 48],
            ['name' => 'عمي موسى', 'wilaya_id' => 48],
            ['name' => 'واريزان', 'wilaya_id' => 48],
            ['name' => 'مرجة سيدي عابد', 'wilaya_id' => 48],
            ['name' => 'أولاد سيدي الميهوب', 'wilaya_id' => 48],
            ['name' => 'بن داود', 'wilaya_id' => 48],
            ['name' => 'وادي رهيو', 'wilaya_id' => 48],
            ['name' => 'الحاسي', 'wilaya_id' => 48],
            ['name' => 'سيدي أمحمد بن علي', 'wilaya_id' => 48],
            ['name' => 'مديونة', 'wilaya_id' => 48],
            ['name' => 'بني زنطيس', 'wilaya_id' => 48],
            ['name' => 'وادي الجمعة', 'wilaya_id' => 48],
            ['name' => 'لحلاف', 'wilaya_id' => 48],
            ['name' => 'غليزان', 'wilaya_id' => 48],
            ['name' => 'الحمادنة', 'wilaya_id' => 48],
            ['name' => 'الرمكة', 'wilaya_id' => 48],
            ['name' => 'تنركوك', 'wilaya_id' => 49],
            ['name' => 'تيميمون', 'wilaya_id' => 49],
            ['name' => 'أولاد السعيد', 'wilaya_id' => 49],
            ['name' => 'المطارفة', 'wilaya_id' => 49],
            ['name' => 'طالمين', 'wilaya_id' => 49],
            ['name' => 'أولاد عيسى', 'wilaya_id' => 49],
            ['name' => 'شروين', 'wilaya_id' => 49],
            ['name' => 'أوقروت', 'wilaya_id' => 49],
            ['name' => 'دلدول', 'wilaya_id' => 49],
            ['name' => 'قصر قدور', 'wilaya_id' => 49],
            ['name' => 'تيمياوين', 'wilaya_id' => 50],
            ['name' => 'برج باجي مختار', 'wilaya_id' => 50],
            ['name' => 'رأس الميعاد', 'wilaya_id' => 51],
            ['name' => 'بسباس', 'wilaya_id' => 51],
            ['name' => 'سيدي  خالد', 'wilaya_id' => 51],
            ['name' => 'الدوسن', 'wilaya_id' => 51],
            ['name' => 'الشعيبة', 'wilaya_id' => 51],
            ['name' => 'أولاد جلال', 'wilaya_id' => 51],
            ['name' => 'بني عباس', 'wilaya_id' => 52],
            ['name' => 'تامترت', 'wilaya_id' => 52],
            ['name' => 'إقلي', 'wilaya_id' => 52],
            ['name' => 'الواتة', 'wilaya_id' => 52],
            ['name' => 'أولاد خضير', 'wilaya_id' => 52],
            ['name' => 'كرزاز', 'wilaya_id' => 52],
            ['name' => 'تيمودي', 'wilaya_id' => 52],
            ['name' => 'القصابي', 'wilaya_id' => 52],
            ['name' => 'بن يخلف', 'wilaya_id' => 52],
            ['name' => 'إينغر', 'wilaya_id' => 53],
            ['name' => 'عين صالح', 'wilaya_id' => 53],
            ['name' => 'فقارة الزوى', 'wilaya_id' => 53],
            ['name' => 'تين زواتين', 'wilaya_id' => 54],
            ['name' => 'عين قزام', 'wilaya_id' => 54],
            ['name' => 'تماسين', 'wilaya_id' => 55],
            ['name' => 'سيدي سليمان', 'wilaya_id' => 55],
            ['name' => 'المقارين', 'wilaya_id' => 55],
            ['name' => 'النزلة', 'wilaya_id' => 55],
            ['name' => 'بلدة اعمر', 'wilaya_id' => 55],
            ['name' => 'تبسبست', 'wilaya_id' => 55],
            ['name' => 'تقرت', 'wilaya_id' => 55],
            ['name' => 'الطيبات', 'wilaya_id' => 55],
            ['name' => 'العالية', 'wilaya_id' => 55],
            ['name' => 'الحجيرة', 'wilaya_id' => 55],
            ['name' => 'بن ناصر', 'wilaya_id' => 55],
            ['name' => 'المنقر', 'wilaya_id' => 55],
            ['name' => 'الزاوية العابدية', 'wilaya_id' => 55],
            ['name' => 'جانت', 'wilaya_id' => 56],
            ['name' => 'برج الحواس', 'wilaya_id' => 56],
            ['name' => 'أم الطيور', 'wilaya_id' => 57],
            ['name' => 'سيدي عمران', 'wilaya_id' => 57],
            ['name' => 'المرارة', 'wilaya_id' => 57],
            ['name' => 'جامعة', 'wilaya_id' => 57],
            ['name' => 'تندلة', 'wilaya_id' => 57],
            ['name' => 'المغير', 'wilaya_id' => 57],
            ['name' => 'سطيل', 'wilaya_id' => 57],
            ['name' => 'سيدي خليل', 'wilaya_id' => 57],
            ['name' => 'المنيعة', 'wilaya_id' => 58],
            ['name' => 'حاسي القارة', 'wilaya_id' => 58],
            ['name' => 'حاسي الفحل', 'wilaya_id' => 58],
        ];

        DB::table('communes')->insert($communes);
    }
}
